Repository TTTM-Mavericks/smart-tailor-FE, pull requests merged in 2024-08, with the labels that each got.

#79 Revert 65 feature fe0030 create manage process with role brand
  package-lock.json
  package.json
  src/api/ApiConfig.tsx
  src/assets/img/homeimage.png
  src/pages/Authentication/SignIn/SignInScreen.tsx
  src/pages/BrandManagement/BrandOrderProcessing/BrandManageOrderProcessingComponent.tsx
  src/pages/BrandManagement/GlobalComponent/Dialog/BrandProductivity/BrandProductivityInputDialog.tsx
  src/pages/BrandManagement/GlobalComponent/NavBarComponent/NavbarComponent.tsx
  src/pages/BrandManagement/GlobalComponent/Notification/NotificationBrandComponent.tsx
  src/pages/BrandManagement/GlobalComponent/Notification/NotificationComponent.jsx
  src/pages/BrandManagement/GlobalComponent/Notification/test.tsx
  src/pages/BrandManagement/GlobalComponent/SideBarComponent/SideBarComponent.tsx
  src/pages/BrandManagement/ManageMaterial/DashboardManageMaterial/DashBoardManageMaterialComponent.tsx
  src/pages/BrandManagement/ManageNotification/NotificationPageComponent.tsx
  src/pages/BrandManagement/ManageOrder/BrandOrderManagement/ManageOrderScreen.tsx
  src/pages/BrandManagement/index.tsx
  src/pages/EmployeeManagement/ManageOrder/EmployeeOrderManagement/EmployeeManageOrderScreen/ManageOrderScreen.tsx
  src/pages/EmployeeManagement/ManageOrder/EmployeeOrderManagement/EmployeeManageOrderScreen/ViewSampleUpdateDialog.tsx
  src/pages/Home/Home.module.scss
  src/pages/Home/HomeScreen.tsx
  src/pages/Order/Components/Dialog/ViewProgessOfProduct/ViewProgessOfProductDialog.tsx
Labels: fIX-bug, update, feature, reviewing

#80 Revert 65 feature fe0030 create manage process with role brand
  src/pages/AboutUs/AboutUsScreen.tsx
  src/pages/AccountantManagement/AccountantDashboard/AccountantDashboardScreen.tsx
  src/pages/AccountantManagement/DashboardAccountant/DashboardAccountantScreens.tsx
  src/pages/AccountantManagement/GlobalComponent/CustomToolBar/CustomToolBar.tsx
  src/pages/AccountantManagement/GlobalComponent/Error404/Error404Component.tsx
  src/pages/AccountantManagement/GlobalComponent/Notification/NotificationWithSocketIOComponent.tsx
  src/pages/AdminManagement/AdminProfile/AdminProfileComponent.tsx
  src/pages/AdminManagement/BarChart/BarChartScreens.tsx
  src/pages/AdminManagement/CardInformationDetail/CardInformationDetailComponent.tsx
  src/pages/AdminManagement/CardInformationDetail/CardinformationScreen.tsx
  src/pages/AdminManagement/DashboardAdmin/DashboardAdminScreens.tsx
  src/pages/AdminManagement/ExpertTailoring/AddEachWithHand/AddEachExpertTailoringWithHandScreens.tsx
  src/pages/AdminManagement/ExpertTailoring/AddEachWithHand/AddEachWithHandStyles.module.scss
  src/pages/AdminManagement/ExpertTailoring/AddMultipleExpertTailoringWithExcel/AddMultipleExpertTailoringComponent.tsx
  src/pages/AdminManagement/ExpertTailoring/AddMultipleExpertTailoringWithExcel/AddMultipleExpertTailoringStyles.module.scss
  src/pages/AdminManagement/ExpertTailoring/AddMultipleExpertTailoringWithExcel/CRUDWithExcelTable/AddMaterialInExcelTable.tsx
  src/pages/AdminManagement/ExpertTailoring/AddMultipleExpertTailoringWithExcel/CRUDWithExcelTable/EditMultipleMaterialInExcelTable.tsx
  src/pages/AdminManagement/ExpertTailoring/AddMultipleExpertTailoringWithExcel/CRUDWithExcelTable/EditMultipleMaterialInExcelTableStyles.module.scss
  src/pages/AdminManagement/ExpertTailoring/DashboardManagerExpertTailoring/DashBoardManageMaterialComponent.tsx
  src/pages/AdminManagement/ExpertTailoring/DashboardManagerExpertTailoring/DashBoardMaterialStyle.module.scss
  src/pages/AdminManagement/ExpertTailoring/ManagerExpertTailoringManagement/ManagerEditExpertTailoring/EditExpertTailoringPopUpScreens.tsx
  src/pages/AdminManagement/ExpertTailoring/ManagerExpertTailoringManagement/ManagerEditExpertTailoring/EditExpertTailoringPopUpStyles.module.scss
  src/pages/AdminManagement/ExpertTailoring/ManagerExpertTailoringManagement/ManagerManageScreen/ManageExpertTailoringScreens.tsx
  src/pages/AdminManagement/ExpertTailoring/ManagerExpertTailoringManagement/ManagerManageScreen/ManageExpertTailoringStyle.module.scss
  src/pages/AdminManagement/ExpertTailoring/TestDash.tsx
  src/pages/AdminManagement/GeographyChart/GeographyChartScreens.tsx
  src/pages/AdminManagement/GlobalComponent/CustomToolBar/CustomToolBar.tsx
  src/pages/AdminManagement/GlobalComponent/Error404/Error404Component.tsx
  src/pages/AdminManagement/GlobalComponent/NavbarComponent/Navbar1111.tsx
  src/pages/AdminManagement/GlobalComponent/Notification/NotificationWithSocketIOComponent.tsx
  src/pages/AdminManagement/GlobalComponent/ProgressCircle/ProgressCircleComponent.tsx
  src/pages/AdminManagement/LineChart/LineChartScreens.tsx
  src/pages/Home/HomeScreen.tsx
Labels: fIX-bug, update, feature, reviewing

#82 Revert 65 feature fe0030 create manage process with role brand
  package-lock.json
  package.json
  src/models/BrandUploadInforModel.tsx
  src/pages/AccountantManagement/AccountantManagePaymentForBrand/AccountantManagePaymentForBrandComponent.tsx
  src/pages/AdminManagement/LineChart/LineChartScreens.tsx
  src/pages/AdminManagement/ManageCategory/AddEachWithHand/AddEachCategoryWithHandScreens.tsx
  src/pages/AdminManagement/ManageCategory/AddMultipleCategoryWithExcel/AddMultipleMaterialComponent.tsx
  src/pages/AdminManagement/ManageCategory/AddMultipleCategoryWithExcel/AddMultipleMaterialStyles.module.scss
  src/pages/AdminManagement/ManageCategory/AddMultipleCategoryWithExcel/CRUDWithExcelTable/AddMaterialInExcelTable.tsx
  src/pages/AdminManagement/ManageCategory/AddMultipleCategoryWithExcel/CRUDWithExcelTable/EditMultipleMaterialInExcelTable.tsx
  src/pages/AdminManagement/ManageCategory/AddMultipleCategoryWithExcel/CRUDWithExcelTable/EditMultipleMaterialInExcelTableStyles.module.scss
  src/pages/AdminManagement/ManageCategory/AdminCategoryManagement/AdminEditMaterial/EditMaterialPopUpScreens.tsx
  src/pages/AdminManagement/ManageCategory/AdminCategoryManagement/AdminManagerScreen/ManageCategoryScreens.tsx
  src/pages/AdminManagement/ManageInvoice/ManageInvoiceScreens.tsx
  src/pages/AdminManagement/ManagePrice/AddManualPrice/AddPriceScreens.tsx
  src/pages/AdminManagement/ManagePrice/AdminPriceManagement/AdminEditPrice/EditPricePopUpScreens.tsx
  src/pages/Authentication/SignIn/SignInScreen.tsx
  src/pages/BrandManagement/BrandUploadInfor/BrandUploadInforComponent.tsx
  src/pages/BrandManagement/BrandUploadInfor/Test.tsx
  src/pages/BrandManagement/GlobalComponent/SideBarComponent/SideBarComponent.tsx
  src/pages/BrandManagement/GlobalComponent/WaitingProcess/WaitingProcessComponent.tsx
  src/pages/BrandManagement/ManageMaterial/DashboardManageMaterial/DashBoardManageMaterialComponent.tsx
  src/pages/BrandManagement/ManageOrder/BrandOrderManagement/ManageOrderScreen.tsx
  src/pages/ContactUs/ContactUsScreen.tsx
  src/pages/EmployeeManagement/GlobalComponent/SideBarComponent/SideBarComponent.tsx
  src/pages/EmployeeManagement/ManageOrder/EmployeeOrderManagement/EmployeeManageOrderScreen/ManageOrderScreen.tsx
  src/pages/FilterProduct/ProductFilterScreen/FilterProductScreen.tsx
  src/pages/ManagerManagement/ManageBrand/ManagerBrandManagement/ManagerManageBrandScreen/ManageBrandScreens.tsx
Labels: fIX-bug, update, feature, reviewing

#84 [FE0030] Update Excel Add Material
  src/pages/AdminManagement/ManageMaterials/AddMultipleMaterialWithExcel/AddMultipleMaterialComponent.tsx
  src/pages/BrandManagement/ManageMaterial/CRUDMaterialWithExcelTable/AddMultipleInExcelTable/AddMultipleMaterialComponent.tsx
  src/pages/Home/HomeScreen.tsx
Labels: fIX-bug, update, feature, reviewing

#85 [FE0030] Update UI Of Brand And Admin
  src/api/ApiConfig.tsx
  src/pages/AdminManagement/ManageMaterials/AddMultipleMaterialWithExcel/AddMultipleMaterialComponent.tsx
  src/pages/BrandManagement/BrandProfile/BrandProfileComponent.tsx
  src/pages/BrandManagement/BrandUploadInfor/BrandUploadInforComponent.tsx
  src/pages/BrandManagement/GlobalComponent/SideBarComponent/SideBarComponent.tsx
  src/pages/BrandManagement/ManageMaterial/CRUDMaterialWithExcelTable/AddMultipleInExcelTable/AddMultipleMaterialComponent.tsx
  src/pages/BrandManagement/ManageOrder/BrandOrderManagement/ManageOrderScreen.tsx
  src/pages/EmployeeManagement/ManageOrder/EmployeeOrderManagement/EmployeeManageOrderScreen/ManageOrderScreen.tsx
  src/pages/EmployeeManagement/ManageReport/EmployeeReportManagement/EmployeeManageReportScreen/ManageReportScreen.tsx
Labels: fIX-bug, update, feature, reviewing

#88 Revert 65 feature fe0030 create manage process with role brand
  src/api/ApiConfig.tsx
  src/models/ManagerBrandModel.tsx
  src/pages/AdminManagement/ManageMaterials/AddMultipleMaterialWithExcel/AddMultipleMaterialComponent.tsx
  src/pages/BrandManagement/ManageMaterial/CRUDMaterialWithExcelTable/AddMultipleInExcelTable/AddMultipleMaterialComponent.tsx
  src/pages/ManagerManagement/ManageBrand/ManagerBrandManagement/ManagerManageBrandScreen/ManageBrandScreens.tsx
Labels: fIX-bug, update, feature, reviewing

#91 Revert 65 feature fe0030 create manage process with role brand
  src/App.jsx
  src/models/BrandManageOrderModel.tsx
  src/models/EmployeeManageOrderModel.tsx
  src/models/EmployeeManageReportModel.tsx
  src/pages/AboutUs/test.tsx
  src/pages/AccountantManagement/GlobalComponent/NavbarComponent/NavbarComponent.tsx
  src/pages/AdminManagement/GlobalComponent/NavbarComponent/NavbarComponent.tsx
  src/pages/AdminManagement/GlobalComponent/SidebarComponent/SidebarComponent.tsx
  src/pages/AdminManagement/ManageCategory/AddEachWithHand/AddEachCategoryWithHandScreens.tsx
  src/pages/AdminManagement/ManageCategory/AdminCategoryManagement/AdminEditMaterial/EditMaterialPopUpScreens.tsx
  src/pages/AdminManagement/ManageCategory/AdminCategoryManagement/AdminManagerScreen/ManageCategoryScreens.tsx
  src/pages/AdminManagement/ManageMaterials/AddEachWithHand/AddEachMaterialWithHandScreens.tsx
  src/pages/AdminManagement/ManageMaterials/AddMultipleMaterialWithExcel/AddMultipleMaterialComponent.tsx
  src/pages/AdminManagement/ManageMaterials/AdminMaterialManagerment/AdminEditMaterial/EditMaterialPopUpScreens.tsx
  src/pages/AdminManagement/ManageMaterials/AdminMaterialManagerment/AdminManagerScreen/ManageMaterialScreens.tsx
  src/pages/AdminManagement/ManagePrice/AddManualPrice/AddPriceScreens.tsx
  src/pages/AdminManagement/ManagePrice/AdminPriceManagement/AdminEditPrice/EditPricePopUpScreens.tsx
  src/pages/AdminManagement/ManagePrice/AdminPriceManagement/AdminManagementScreen/ManagePriceScreens.tsx
  src/pages/AdminManagement/ManageSize/AddManualSize/AddSizeScreens.tsx
  src/pages/AdminManagement/ManageSize/AdminSizeManagement/AdminEditSize/EditSizePopUpScreens.tsx
  src/pages/AdminManagement/ManageSize/AdminSizeManagement/AdminManagerScreen/ManageSizeScreens.tsx
  src/pages/AdminManagement/SystemConfigurationAdministration/SystemConfigurationAdministrationScreen.tsx
  src/pages/BrandManagement/GlobalComponent/SideBarComponent/SideBarComponent.tsx
  src/pages/BrandManagement/ManageMaterial/CRUDMaterialWithExcelTable/AddMultipleInExcelTable/AddMultipleMaterialComponent.tsx
  src/pages/BrandManagement/ManageMaterial/MaterialManage/EditMaterial/EditMaterialPopUpScreens.tsx
  src/pages/BrandManagement/ManageMaterial/MaterialManage/MaterialManageScreens.tsx
  src/pages/BrandManagement/ManageOrder/BrandOrderManagement/ManageOrderScreen.tsx
  src/pages/BrandManagement/ManagePrice/AddManualPrice/AddPriceScreens.tsx
  src/pages/BrandManagement/ManagePrice/BrandPriceManagement/BrandEditPrice/EditPricePopUpScreens.tsx
  src/pages/BrandManagement/ManagePrice/BrandPriceManagement/BrandManagementScreen/ManagePriceScreens.tsx
  src/pages/EmployeeManagement/GlobalComponent/NavBarComponent/NavbarComponent.tsx
  src/pages/EmployeeManagement/GlobalComponent/SideBarComponent/SideBarComponent.tsx
  src/pages/EmployeeManagement/ManageBrand/EmployeeBrandManagement/EmployeeManageBrandScreen/ManageBrandScreen.tsx
  src/pages/EmployeeManagement/ManageCustomer/ManageCustomerScreen.tsx
  src/pages/EmployeeManagement/ManageOrder/EmployeeOrderManagement/EmployeeManageOrderScreen/ManageOrderScreen.tsx
  src/pages/EmployeeManagement/ManageReport/EmployeeReportManagement/EmployeeManageReportScreen/ManageReportScreen.tsx
  src/pages/EmployeeManagement/ManageTransaction/EmployeeTransactionManagement/EmployeeManageTransactionScreen/ManageTransactionScreen.tsx
  src/pages/ManagerManagement/ExpertTailoring/AddEachWithHand/AddEachExpertTailoringWithHandScreens.tsx
  src/pages/ManagerManagement/ExpertTailoring/AddMultipleExpertTailoringWithExcel/AddMultipleExpertTailoringComponent.tsx
  src/pages/ManagerManagement/ExpertTailoring/ManagerExpertTailoringManagement/ManagerEditExpertTailoring/EditExpertTailoringPopUpScreens.tsx
  src/pages/ManagerManagement/ExpertTailoring/ManagerExpertTailoringManagement/ManagerManageScreen/ManageExpertTailoringScreens.tsx
  src/pages/ManagerManagement/ExpertTailoringMaterial/AddEachWithHand/AddEachExpertTailoringWithHandScreens.tsx
  src/pages/ManagerManagement/ExpertTailoringMaterial/AddMultipleExpertTailoringMaterialWithExcel/AddMultipleExpertTailoringMaterialComponent.tsx
  src/pages/ManagerManagement/ExpertTailoringMaterial/ManagerExpertTailoringMaterialManagement/ManagerManageExpertTailoringMaterialScreen/ManageExpertTailoringMaterialScreens.tsx
  src/pages/ManagerManagement/GlobalComponent/NavBarComponent/NavbarComponent.tsx
  src/pages/ManagerManagement/GlobalComponent/SideBarComponent/SideBarComponent.tsx
  src/pages/ManagerManagement/ManageBrand/ManagerBrandManagement/ManagerManageBrandScreen/ManageBrandScreens.tsx
  src/pages/ManagerManagement/ManageCustomer/ManageCustomerManagement/ManagerManageCustomerScreen/ManageCustomerScreens.tsx
  src/pages/ManagerManagement/ManageEmployee/ManagerEmployeeManagement/ManagerManageEmployeeScreen/ManageEmployeeScreens.tsx
  src/pages/ManagerManagement/ManageTask/ManagerTaskManagement/ManagerManageTaskScreen/ManageTaskScreens.tsx
  src/pages/ManagerManagement/SizeExpertTailoring/AddEachWithHand/AddEachSizeExpertTailoringWithHandScreens.tsx
  src/pages/ManagerManagement/SizeExpertTailoring/AddMultipleSizeExpertTailoring/AddMultipleSizeExpertTailoringComponent.tsx
  src/pages/ManagerManagement/SizeExpertTailoring/ManagerSizeExpertTailoringManagement/ManagerEditSizeExpertTailoring/EditSizeExpertTailoringPopUpScreens.tsx
  src/pages/ManagerManagement/SizeExpertTailoring/ManagerSizeExpertTailoringManagement/ManagerManageScreen/ManageExpertTailoringScreens.tsx
Labels: fIX-bug, update, feature, reviewing

#92 Revert 65 feature fe0030 create manage process with role brand
  src/pages/AccountantManagement/AccountantManagePaymentForBrand/AccountantManagePaymentForBrandComponent.tsx
  src/pages/AdminManagement/ManageMaterials/AdminMaterialManagerment/AdminManagerScreen/ManageMaterialScreens.tsx
  src/pages/AdminManagement/ManagePrice/AdminPriceManagement/AdminManagementScreen/ManagePriceScreens.tsx
  src/pages/BrandManagement/ManageMaterial/MaterialManage/MaterialManageScreens.tsx
  src/pages/BrandManagement/ManageOrder/BrandOrderManagement/ManageOrderScreen.tsx
  src/pages/BrandManagement/ManagePrice/BrandPriceManagement/BrandManagementScreen/ManagePriceScreens.tsx
  src/pages/EmployeeManagement/ManageOrder/EmployeeOrderManagement/EmployeeManageOrderScreen/ManageOrderScreen.tsx
  src/pages/EmployeeManagement/ManageReport/EmployeeReportManagement/EmployeeManageReportScreen/ManageReportScreen.tsx
  src/pages/ManagerManagement/ExpertTailoring/ManagerExpertTailoringManagement/ManagerManageScreen/ManageExpertTailoringScreens.tsx
  src/pages/ManagerManagement/ExpertTailoringMaterial/ManagerExpertTailoringMaterialManagement/ManagerManageExpertTailoringMaterialScreen/ManageExpertTailoringMaterialScreens.tsx
  src/pages/ManagerManagement/SizeExpertTailoring/ManagerSizeExpertTailoringManagement/ManagerManageScreen/ManageExpertTailoringScreens.tsx
Labels: fIX-bug, update, feature, reviewing

#93 [FE0044] Create refund history screen
  src/App.jsx
  src/api/ApiConfig.tsx
  src/assets/index.js
  src/assets/system/GHTK_logo.png
  src/pages/EmployeeManagement/ManageOrder/EmployeeOrderManagement/EmployeeManageOrderScreen/ManageOrderScreen.tsx
  src/pages/Home/HomeScreen.tsx
  src/pages/Order/OrderDetail/OrderDetailScreen.tsx
  src/pages/Order/RefundTransactionHistory/RefundTransactionHistoryScreen.tsx
  src/pages/Order/RefundTransactionHistory/RefundTransactionHistoryStyle.module.scss
  src/pages/Order/index.tsx
Labels: fIX-bug, create, update, feature, reviewing

#94 [FE0058] Create notification processing
  src/App.jsx
  src/components/Notification/NotificationComponent.tsx
Labels: create, feature, reviewing

#95 [FE0044] Update card interface of accountant screen
  src/pages/AccountantManagement/AccountantManagePaymentForBrand/AccountantManagePaymentForBrandComponent.tsx
  src/pages/EmployeeManagement/ManageOrder/EmployeeOrderManagement/EmployeeManageOrderScreen/ManageOrderScreen.tsx
  src/pages/Order/OrderDetail/OrderDetailScreen.tsx
  src/utils/DateUtils.tsx
Labels: create, update, feature, reviewing

#96 [FE0030] Update UI Of Collection And Order History
  src/pages/AccountantManagement/AccountantManagePaymentForBrand/AccountantManagePaymentForBrandComponent.tsx
  src/pages/AdminManagement/ManageCategory/AddEachWithHand/AddEachCategoryWithHandScreens.tsx
  src/pages/AdminManagement/ManageCategory/AdminCategoryManagement/AdminEditMaterial/EditMaterialPopUpScreens.tsx
  src/pages/AdminManagement/ManageMaterials/AddEachWithHand/AddEachMaterialWithHandScreens.tsx
  src/pages/AdminManagement/ManageMaterials/AdminMaterialManagerment/AdminEditMaterial/EditMaterialPopUpScreens.tsx
  src/pages/AdminManagement/ManagePrice/AdminPriceManagement/AdminEditPrice/EditPricePopUpScreens.tsx
  src/pages/AdminManagement/ManageSize/AdminSizeManagement/AdminEditSize/EditSizePopUpScreens.tsx
  src/pages/Authentication/ProfileSetting/ProfileSettingScreen.tsx
  src/pages/BrandManagement/GlobalComponent/NavBarComponent/NavbarComponent.tsx
  src/pages/BrandManagement/ManageMaterial/MaterialManage/EditMaterial/EditMaterialPopUpScreens.tsx
  src/pages/BrandManagement/ManagePrice/BrandPriceManagement/BrandEditPrice/EditPricePopUpScreens.tsx
  src/pages/DesignCollection/DesignCollectionContainer/DesignCollectionScreen.tsx
  src/pages/ManagerManagement/ExpertTailoring/AddEachWithHand/AddEachExpertTailoringWithHandScreens.tsx
  src/pages/ManagerManagement/ExpertTailoring/ManagerExpertTailoringManagement/ManagerEditExpertTailoring/EditExpertTailoringPopUpScreens.tsx
  src/pages/ManagerManagement/ExpertTailoringMaterial/AddEachWithHand/AddEachExpertTailoringWithHandScreens.tsx
  src/pages/ManagerManagement/SizeExpertTailoring/AddEachWithHand/AddEachSizeExpertTailoringWithHandScreens.tsx
  src/pages/ManagerManagement/SizeExpertTailoring/ManagerSizeExpertTailoringManagement/ManagerEditSizeExpertTailoring/EditSizeExpertTailoringPopUpScreens.tsx
  src/pages/Order/Components/Dashboard/DashboardComponent.tsx
  src/pages/Order/Components/Sidebar/SidebarComponent.tsx
  src/pages/Order/OrderHistory/OrderHistoryScreen.tsx
  src/pages/Order/RefundTransactionHistory/RefundTransactionHistoryScreen.tsx
  src/pages/Order/ReportHistory/ReportHistorySreen.tsx
Labels: fIX-bug, update, feature, reviewing

#97 [FE0044] Update conflict
  src/components/Notification/NotificationComponent.tsx
  src/pages/AccountantManagement/AccountantManagePaymentForBrand/AccountantManagePaymentForBrandComponent.tsx
  src/pages/Order/RefundTransactionHistory/RefundTransactionHistoryScreen.tsx
Labels: fIX-bug, update, reviewing

#98 [FE0030] Update UI
  src/pages/AccountantManagement/AccountantManagePaymentForBrand/AccountantManagePaymentForBrandComponent.tsx
Labels: update, feature, reviewing

#107 Revert 65 feature fe0030 create manage process with role brand
  src/App.jsx
  src/models/CustomerModel.tsx
  src/models/EmployeeModel.tsx
  src/models/ManagerExpertTaloringMaterialModel.tsx
  src/pages/AccountantManagement/AccountantManagePaymentForBrand/AccountantManagePaymentForBrandComponent.tsx
  src/pages/AccountantManagement/DashboardAccountant/DashboardAccountantScreens.tsx
  src/pages/AccountantManagement/GlobalComponent/SidebarComponent/SidebarComponent.tsx
  src/pages/AdminManagement/BarChart/BarChartScreens.tsx
  src/pages/AdminManagement/BarChart/DataTestBarChart.tsx
  src/pages/AdminManagement/DashboardAdmin/DashboardAdminScreens.tsx
  src/pages/AdminManagement/GlobalComponent/SidebarComponent/SidebarComponent.tsx
  src/pages/AdminManagement/LineChart/DataTestLineChart.tsx
  src/pages/AdminManagement/LineChart/LineChartScreens.tsx
  src/pages/AdminManagement/ManageInvoice/ManageInvoiceScreens.tsx
  src/pages/AdminManagement/ManageMaterials/AdminMaterialManagerment/AdminManagerScreen/ManageMaterialScreens.tsx
  src/pages/AdminManagement/PieChart/PieDataTest.tsx
  src/pages/BrandManagement/ManageOrder/BrandOrderManagement/ManageOrderScreen.tsx
  src/pages/BrandManagement/ManagePrice/BrandPriceManagement/BrandManagementScreen/ManagePriceScreens.tsx
  src/pages/EmployeeManagement/ManageOrder/EmployeeOrderManagement/EmployeeManageOrderScreen/ManageOrderScreen.tsx
  src/pages/EmployeeManagement/ManageReport/EmployeeReportManagement/EmployeeManageReportScreen/ManageReportScreen.tsx
  src/pages/ManagerManagement/ExpertTailoring/DashboardManagerExpertTailoring/DashBoardManageExpertTailoringComponent.tsx
  src/pages/ManagerManagement/ExpertTailoring/ManagerExpertTailoringManagement/ManagerManageScreen/ManageExpertTailoringScreens.tsx
  src/pages/ManagerManagement/ExpertTailoringMaterial/ManagerExpertTailoringMaterialManagement/ManagerManageExpertTailoringMaterialScreen/ManageExpertTailoringMaterialScreens.tsx
  src/pages/ManagerManagement/GlobalComponent/SideBarComponent/SideBarComponent.tsx
  src/pages/ManagerManagement/ManageBrand/ManagerBrandManagement/ManagerManageBrandScreen/ManageBrandScreens.tsx
  src/pages/ManagerManagement/ManageCustomer/ManageCustomerManagement/ManagerManageCustomerScreen/ManageCustomerScreens.tsx
  src/pages/ManagerManagement/ManageEmployee/ManagerEmployeeManagement/ManagerManageEmployeeScreen/ManageEmployeeScreens.tsx
  src/pages/ManagerManagement/SizeExpertTailoring/ManagerSizeExpertTailoringManagement/ManagerManageScreen/ManageExpertTailoringScreens.tsx
  src/root/ColorSystem.tsx
Labels: update, feature, reviewing

#108 [FE0044] Update system propertises
  src/api/ApiConfig.tsx
  src/components/Dialog/PaymentDialog/PaymentOrderDialogComponent.tsx
  src/models/UltilModel.tsx
  src/pages/AccountantManagement/AccountantManagePaymentForBrand/AccountantManagePaymentForBrandComponent.tsx
  src/pages/AccountantManagement/AccountantManageRefundPayment/AccountantManageRefundPaymentForBrandComponent.tsx
  src/pages/AdminManagement/GlobalComponent/NavbarComponent/NavbarComponent.tsx
  src/pages/AdminManagement/SystemConfigurationAdministration/SystemConfigurationAdministrationScreen.tsx
  src/pages/EmployeeManagement/ManageOrder/EmployeeOrderManagement/EmployeeManageOrderScreen/ManageOrderScreen.tsx
Labels: fIX-bug, create, update, feature, reviewing

#109 Revert 65 feature fe0030 create manage process with role brand
  src/api/ApiConfig.tsx
  src/pages/AccountantManagement/AccountantManagePaymentForBrand/AccountantManagePaymentForBrandComponent.tsx
  src/pages/AdminManagement/BarChart/BarChartComponent.tsx
  src/pages/AdminManagement/CardInformationDetail/CardInformationDetailComponent.tsx
  src/pages/AdminManagement/DashboardAdmin/DashboardAdminScreens.tsx
  src/pages/AdminManagement/ManageMaterials/AddEachWithHand/AddEachMaterialWithHandScreens.tsx
  src/pages/AdminManagement/ManageMaterials/AddMultipleMaterialWithExcel/AddMultipleMaterialComponent.tsx
  src/pages/AdminManagement/ManageMaterials/AdminMaterialManagerment/AdminEditMaterial/EditMaterialPopUpScreens.tsx
  src/pages/AdminManagement/ManageMaterials/AdminMaterialManagerment/AdminManagerScreen/ManageMaterialScreens.tsx
  src/pages/AdminManagement/ManagePrice/AdminPriceManagement/AdminManagementScreen/ManagePriceScreens.tsx
  src/pages/AdminManagement/PieChart/PieChartComponent.tsx
  src/pages/AdminManagement/PieChart/PieChartScreens.tsx
  src/pages/AdminManagement/PieChart/PieDataTest.tsx
  src/pages/BrandManagement/ManageMaterial/AddEachWithHand/AddEachMaterialWithHandScreens.tsx
  src/pages/BrandManagement/ManageMaterial/CRUDMaterialWithExcelTable/AddMultipleInExcelTable/AddMultipleMaterialComponent.tsx
  src/pages/BrandManagement/ManageMaterial/MaterialManage/EditMaterial/EditMaterialPopUpScreens.tsx
  src/pages/BrandManagement/ManageOrder/BrandOrderManagement/ManageOrderScreen.tsx
  src/pages/BrandManagement/ManagePrice/BrandPriceManagement/BrandManagementScreen/ManagePriceScreens.tsx
  src/pages/Order/AllTransactionHistory/AllTransactionHistoryComponent.tsx
  src/pages/Order/OrderHistory/OrderHistoryScreen.tsx
  src/pages/Order/RefundTransactionHistory/RefundTransactionHistoryScreen.tsx
  src/pages/Order/ReportHistory/ReportHistoryComponent.tsx
Labels: fIX-bug, update, feature, reviewing

#110 Revert 65 feature fe0030 create manage process with role brand
  src/api/ApiConfig.tsx
  src/pages/AccountantManagement/AccountantDashboard/AccountantDashboardScreen.tsx
  src/pages/AccountantManagement/DashboardAccountant/DashboardAccountantScreens.tsx
  src/pages/AdminManagement/BarChart/BarChartScreens.tsx
  src/pages/AdminManagement/BarChart/DataTestBarChart.tsx
  src/pages/AdminManagement/CardInformationDetail/CardInformationDetailComponent.tsx
  src/pages/AdminManagement/DashboardAdmin/DashboardAdminScreens.tsx
  src/pages/AdminManagement/ManageCategory/AddEachWithHand/AddEachCategoryWithHandScreens.tsx
  src/pages/AdminManagement/ManageCategory/AdminCategoryManagement/AdminEditMaterial/EditMaterialPopUpScreens.tsx
  src/pages/AdminManagement/ManageCategory/AdminCategoryManagement/AdminManagerScreen/ManageCategoryScreens.tsx
  src/pages/AdminManagement/ManagePrice/AddManualPrice/AddPriceScreens.tsx
  src/pages/AdminManagement/ManagePrice/AdminPriceManagement/AdminEditPrice/EditPricePopUpScreens.tsx
  src/pages/AdminManagement/ManagePrice/AdminPriceManagement/AdminManagementScreen/ManagePriceScreens.tsx
  src/pages/AdminManagement/ManageSize/AddManualSize/AddSizeScreens.tsx
  src/pages/AdminManagement/ManageSize/AdminSizeManagement/AdminEditSize/EditSizePopUpScreens.tsx
  src/pages/AdminManagement/ManageSize/AdminSizeManagement/AdminManagerScreen/ManageSizeScreens.tsx
  src/pages/AdminManagement/PieChart/PieChartScreens.tsx
  src/pages/BrandManagement/ManagePrice/AddManualPrice/AddPriceScreens.tsx
  src/pages/BrandManagement/ManagePrice/BrandPriceManagement/BrandEditPrice/EditPricePopUpScreens.tsx
  src/pages/BrandManagement/ManagePrice/BrandPriceManagement/BrandManagementScreen/ManagePriceScreens.tsx
  src/pages/ManagerManagement/ExpertTailoring/AddEachWithHand/AddEachExpertTailoringWithHandScreens.tsx
  src/pages/ManagerManagement/ExpertTailoring/AddMultipleExpertTailoringWithExcel/AddMultipleExpertTailoringComponent.tsx
  src/pages/ManagerManagement/ExpertTailoring/ManagerExpertTailoringManagement/ManagerEditExpertTailoring/EditExpertTailoringPopUpScreens.tsx
  src/pages/ManagerManagement/ExpertTailoring/ManagerExpertTailoringManagement/ManagerManageScreen/ManageExpertTailoringScreens.tsx
  src/pages/ManagerManagement/ExpertTailoringMaterial/AddEachWithHand/AddEachExpertTailoringWithHandScreens.tsx
  src/pages/ManagerManagement/ExpertTailoringMaterial/AddMultipleExpertTailoringMaterialWithExcel/AddMultipleExpertTailoringMaterialComponent.tsx
  src/pages/ManagerManagement/ExpertTailoringMaterial/ManagerExpertTailoringMaterialManagement/ManagerEditExpertTailoringMaterial/EditExpertTailoringMaterialPopUpScreens.tsx
  src/pages/ManagerManagement/ExpertTailoringMaterial/ManagerExpertTailoringMaterialManagement/ManagerManageExpertTailoringMaterialScreen/ManageExpertTailoringMaterialScreens.tsx
  src/pages/ManagerManagement/ManageBrand/ManagerBrandManagement/ManagerEditBrand/EditBrandPopUpScreens.tsx
  src/pages/ManagerManagement/ManageBrand/ManagerBrandManagement/ManagerManageBrandScreen/ManageBrandScreens.tsx
  src/pages/ManagerManagement/ManageCustomer/ManageCustomerManagement/ManagerManageCustomerScreen/ManageCustomerScreens.tsx
  src/pages/ManagerManagement/ManageEmployee/ManagerEmployeeManagement/ManagerManageEmployeeScreen/ManageEmployeeScreens.tsx
  src/pages/ManagerManagement/SizeExpertTailoring/AddEachWithHand/AddEachSizeExpertTailoringWithHandScreens.tsx
  src/pages/ManagerManagement/SizeExpertTailoring/AddMultipleSizeExpertTailoring/AddMultipleSizeExpertTailoringComponent.tsx
  src/pages/ManagerManagement/SizeExpertTailoring/ManagerSizeExpertTailoringManagement/ManagerManageScreen/ManageExpertTailoringScreens.tsx
Labels: fIX-bug, update, feature

#111 [FE0044] Update material detail
  src/App.jsx
  src/api/ApiConfig.tsx
  src/canvas/Shirt.jsx
  src/components/Card/ProductCard/ProductCard.tsx
  src/components/Dialog/FinalCheckingProductsDialog/FinalCheckingProductsDialogComponent.tsx
  src/components/Dialog/FinalCheckingProductsDialog/FinalCheckingProductsDialogStyle.module.scss
  src/components/Header/HeaderComponent.tsx
  src/components/Notification/NotificationComponent.tsx
  src/models/EmployeeManageOrderModel.tsx
  src/pages/AccountantManagement/AccountantDashboard/AccountantDashboardScreen.tsx
  src/pages/AccountantManagement/AccountantManagePaymentForBrand/AccountantManagePaymentForBrandComponent.tsx
  src/pages/AccountantManagement/AccountantManageRefundPayment/AccountantManageRefundPaymentForBrandComponent.tsx
  src/pages/AdminManagement/CardInformationDetail/CardInformationDetailComponent.tsx
  src/pages/AdminManagement/SystemConfigurationAdministration/SystemConfigurationAdministrationScreen.tsx
  src/pages/BrandManagement/BrandManageTransaction/BrandManageTransactionComponent.tsx
  src/pages/BrandManagement/BrandOrderManagement/OrderRequestDetailsComponent.tsx
  src/pages/BrandManagement/GlobalComponent/Dialog/UploadProgcessSampleProduct/BrandUploadProgcessSampleProduct.tsx
  src/pages/BrandManagement/ManageOrder/BrandOrderManagement/ManageOrderScreen.tsx
  src/pages/CustomDesign/CustomDesignScreen.tsx
  src/pages/EmployeeManagement/ManageOrder/EmployeeOrderManagement/EmployeeManageOrderScreen/ManageOrderScreen.tsx
  src/pages/EmployeeManagement/ManageOrder/EmployeeOrderManagement/EmployeeManageOrderScreen/ViewSampleUpdateDialog.tsx
  src/pages/EmployeeManagement/ManageReport/EmployeeReportManagement/EmployeeManageReportScreen/ManageReportScreen.tsx
  src/pages/Home/HomeScreen.tsx
  src/pages/Order/AllTransactionHistory/AllTransactionHistoryComponent.tsx
  src/pages/Order/Components/Dialog/ViewFinalCheckingProductsDialog/ViewFinalCheckingProductsDialogComponent.tsx
  src/pages/Order/Components/Dialog/ViewFinalCheckingProductsDialog/ViewFinalCheckingProductsDialogComponentStyle.module.scss
  src/pages/Order/OrderDetail/OrderDetailScreen.tsx
  src/pages/Order/OrderHistory/OrderHistoryScreen.tsx
  src/pages/Order/OrderProduct/OrderProductScreen.tsx
Labels: fIX-bug, create, update, feature, reviewing

#112 [FE0044] Upload brand invoice
  src/components/Header/HeaderComponent.tsx
  src/pages/AccountantManagement/AccountantManagePaymentForBrand/AccountantManagePaymentForBrandComponent.tsx
  src/pages/BrandManagement/GlobalComponent/Dialog/UploadProgcessSampleProduct/BrandUploadProgcessSampleProduct.tsx
  src/pages/Order/Components/Dialog/ViewFinalCheckingProductsDialog/ViewFinalCheckingProductsDialogComponent.tsx
Labels: create, update, feature, reviewing

#114 [FE0044] Update suborder invoice
  src/api/ApiConfig.tsx
  src/models/DesignModel.tsx
  src/pages/AccountantManagement/AccountantManagePaymentForBrand/AccountantManagePaymentForBrandComponent.tsx
  src/pages/EmployeeManagement/ManageReport/EmployeeReportManagement/EmployeeManageReportScreen/ManageReportScreen.tsx
Labels: create, update, feature, reviewing

#115 Revert 65 feature fe0030 create manage process with role brand
  src/components/Dialog/SizeDialog/SizeDialogComponent.tsx
  src/pages/AccountantManagement/AccountantManagePaymentForBrand/AccountantManagePaymentForBrandComponent.tsx
  src/pages/Authentication/ProfileSetting/ProfileSettingScreen.tsx
  src/pages/BrandManagement/BrandProfile/BrandProfileComponent.tsx
  src/pages/BrandManagement/GlobalComponent/Dialog/UploadProgcessSampleProduct/BrandUploadProgcessSampleProduct.tsx
  src/pages/BrandManagement/GlobalComponent/NavBarComponent/NavbarComponent.tsx
  src/pages/EmployeeManagement/ManageOrder/EmployeeOrderManagement/EmployeeManageOrderScreen/ManageOrderScreen.tsx
  src/pages/EmployeeManagement/ManageOrder/EmployeeOrderManagement/EmployeeManageOrderScreen/ViewSampleUpdateDialog.tsx
Labels: fIX-bug, update, feature, reviewing

#116 Revert 65 feature fe0030 create manage process with role brand
  src/pages/AccountantManagement/AccountantManageRefundPayment/AccountantManageRefundPaymentForBrandComponent.tsx
  src/pages/BrandManagement/BrandUploadInfor/BrandUploadInforComponent.tsx
  src/pages/Order/Components/Dialog/PaymentInformationDialog/PaymentInformationDialogComponent.tsx
Labels: fIX-bug, update, feature, reviewing

#117 [FE0044] Update payment
  src/api/ApiConfig.tsx
  src/components/Dialog/PaymentDialog/PaymentFromAccountantToBranđialog.tsx
  src/components/Dialog/PaymentDialog/PaymentOrderDialogComponent.tsx
  src/models/OrderModel.tsx
  src/models/PaymentModel.tsx
  src/pages/AccountantManagement/AccountantManagePaymentForBrand/AccountantManagePaymentForBrandComponent.tsx
  src/pages/BrandManagement/BrandManageTransaction/BrandManageTransactionComponent.tsx
  src/pages/CustomDesign/CustomDesignScreen.tsx
  src/pages/DesignCollection/DesignCollectionContainer/DesignCollectionScreen.tsx
  src/pages/Home/HomeScreen.tsx
  src/pages/Order/AllTransactionHistory/AllTransactionHistoryComponent.tsx
  src/pages/Order/OrderDetail/OrderDetailScreen.tsx
  src/pages/Order/OrderHistory/OrderHistoryScreen.tsx
  src/pages/Order/RefundTransactionHistory/RefundTransactionHistoryScreen.tsx
  src/pages/Order/ReportHistory/ReportHistorySreen.tsx
Labels: fIX-bug, update, feature, reviewing

#118 [FE0044] Update order status
  src/api/ApiConfig.tsx
  src/components/Dialog/RefunctionRequestDialog/CreateRefundInformationDialogComponent.tsx
  src/components/Dialog/RefunctionRequestDialog/RefunctionRequestDialogComponent.tsx
  src/components/Dialog/RefunctionRequestDialog/RefunctionRequestDialogComponentStyle.module.scss
  src/pages/AccountantManagement/AccountantManagePaymentForBrand/AccountantManagePaymentForBrandComponent.tsx
  src/pages/EmployeeManagement/ManageOrder/EmployeeOrderManagement/EmployeeManageOrderScreen/ManageOrderScreen.tsx
  src/pages/EmployeeManagement/ManageReport/EmployeeReportManagement/EmployeeManageReportScreen/ManageReportScreen.tsx
  src/pages/Order/OrderDetail/OrderDetailScreen.tsx
Labels: create, update, feature, reviewing

#120 Revert 65 feature fe0030 create manage process with role brand
  src/pages/AccountantManagement/AccountantManagePaymentForBrand/AccountantManagePaymentForBrandComponent.tsx
  src/pages/AccountantManagement/AccountantManageRefundPayment/AccountantManageRefundPaymentForBrandComponent.tsx
  src/pages/AccountantManagement/GlobalComponent/SidebarComponent/SidebarComponent.tsx
  src/pages/BrandManagement/BrandUploadInfor/BrandUploadInforComponent.tsx
  src/pages/BrandManagement/BrandUploadInfor/BrandUploadInforStyle.module.scss
  src/pages/BrandManagement/GlobalComponent/SideBarComponent/SideBarComponent.tsx
  src/pages/BrandManagement/ManageOrder/BrandOrderManagement/ManageOrderScreen.tsx
  src/pages/EmployeeManagement/GlobalComponent/SideBarComponent/SideBarComponent.tsx
  src/pages/EmployeeManagement/ManageOrder/EmployeeOrderManagement/EmployeeManageOrderScreen/ManageOrderScreen.tsx
  src/pages/EmployeeManagement/ManageReport/EmployeeReportManagement/EmployeeManageReportScreen/ManageReportScreen.tsx
  src/pages/ManagerManagement/ExpertTailoring/ManagerExpertTailoringManagement/ManagerManageScreen/ManageExpertTailoringScreens.tsx
Labels: fIX-bug, update, feature, reviewing

#121 [FE0044] Update processing
  src/assets/index.js
  src/assets/system/cloth_tag.png
  src/components/Dialog/RefunctionRequestDialog/RefunctionRequestDialogComponent.tsx
  src/models/OrderModel.tsx
  src/models/PaymentModel.tsx
  src/pages/AccountantManagement/AccountantManageRefundPayment/AccountantManageRefundPaymentForBrandComponent.tsx
  src/pages/Order/Components/Table/MaterialDetailTableComponent.tsx
  src/pages/Order/Components/Table/PartOfClothAndPriceDetailComponent.tsx
  src/pages/Order/OrderDetail/OrderDetailScreen.tsx
  src/pages/Order/OrderHistory/OrderHistoryScreen.tsx
  src/pages/Order/RefundTransactionHistory/RefundTransactionHistoryScreen.tsx
Labels: fIX-bug, create, update, feature, reviewing

#122 [FE0044] Update price in accountant invoice
  src/components/Dialog/PaymentDialog/PaymentOrderDialogComponent.tsx
  src/pages/AccountantManagement/AccountantManagePaymentForBrand/AccountantManagePaymentForBrandComponent.tsx
  src/pages/Order/Components/Table/PartOfClothAndPriceDetailComponent.tsx
  src/pages/Order/OrderDetail/OrderDetailScreen.tsx
Labels: update, feature, reviewing

#123 [FE0044] Update sample tag
  src/api/ApiConfig.tsx
  src/pages/AccountantManagement/AccountantManageFinedPayment/AccountantManageFinedPaymentComponent.tsx
  src/pages/AccountantManagement/AccountantManageFinedPayment/AccountantManageFinedPaymentComponentStyle.module.scss
  src/pages/AccountantManagement/AccountantManagePaymentForBrand/AccountantManagePaymentForBrandComponent.tsx
  src/pages/AccountantManagement/DashboardAccountant/DashboardAccountantScreens.tsx
  src/pages/AccountantManagement/GlobalComponent/SidebarComponent/SidebarComponent.tsx
  src/pages/BrandManagement/ManageOrder/BrandOrderManagement/ManageOrderScreen.tsx
  src/pages/DesignCollection/DesignCollectionContainer/DesignCollectionScreen.tsx
  src/pages/Order/OrderDetail/OrderDetailScreen.tsx
Labels: update, feature

#125 Revert 65 feature fe0030 create manage process with role brand
  src/models/LaborQuantityModel.tsx
  src/pages/BrandManagement/ManagePrice/AddManualPrice/AddPriceScreens.tsx
  src/pages/BrandManagement/ManagePrice/BrandPriceManagement/BrandEditPrice/EditPricePopUpScreens.tsx
  src/pages/BrandManagement/ManagePrice/BrandPriceManagement/BrandManagementScreen/ManagePriceScreens.tsx
Labels: fIX-bug, update, feature, reviewing

#126 Revert 65 feature fe0030 create manage process with role brand
  src/models/ManagerExpertTailoringModel.tsx
  src/pages/BrandManagement/BrandUploadInfor/BrandUploadInforComponent.tsx
  src/pages/BrandManagement/ManagePrice/AddManualPrice/AddPriceScreens.tsx
  src/pages/ManagerManagement/ExpertTailoring/AddEachWithHand/AddEachExpertTailoringWithHandScreens.tsx
  src/pages/ManagerManagement/ExpertTailoring/AddEachWithHand/bebe.json
  src/pages/ManagerManagement/ExpertTailoring/ManagerExpertTailoringManagement/ManagerEditExpertTailoring/EditExpertTailoringPopUpScreens.tsx
Labels: fIX-bug, update, feature, reviewing

#127 [FE0044] Update design
  src/canvas/Hoodie.jsx
  src/components/Dialog/CommingSoonDialog/ComingSoonDialog.tsx
  src/models/DesignModel.tsx
  src/pages/AccountantManagement/AccountantManagePaymentForBrand/AccountantManagePaymentForBrandComponent.tsx
  src/pages/BrandManagement/GlobalComponent/Dialog/UploadProgcessSampleProduct/BrandUploadProgcessSampleProduct.tsx
  src/pages/BrandManagement/ManageOrder/BrandOrderManagement/ManageOrderScreen.tsx
  src/pages/CustomDesign/Components/MaterialDetail/MaterialDetailComponent.tsx
  src/pages/CustomDesign/CustomDesignScreen.tsx
  src/pages/EmployeeManagement/ManageOrder/EmployeeOrderManagement/EmployeeManageOrderScreen/ManageOrderScreen.tsx
  src/pages/Order/OrderDetail/OrderDetailScreen.tsx
  src/pages/Order/RefundTransactionHistory/RefundTransactionHistoryScreen.tsx
Labels: fIX-bug, merged, update, feature, reviewing

#128 [FE0044] Update interface for order processing
  src/components/Dialog/RefunctionRequestDialog/CreateRefundInformationDialogComponent.tsx
  src/components/Notification/NotificationComponent.tsx
  src/pages/AccountantManagement/AccountantDashboard/AccountantDashboardScreen.tsx
  src/pages/AccountantManagement/AccountantManagePaymentForBrand/AccountantManagePaymentForBrandComponent.tsx
  src/pages/Authentication/ProfileSetting/ProfileSettingScreen.tsx
  src/pages/BrandManagement/BrandManageTransaction/BrandManageTransactionComponent.tsx
  src/pages/BrandManagement/BrandUploadInfor/BrandUploadInforComponent.tsx
  src/pages/DesignCollection/DesignCollectionContainer/DesignCollectionScreen.tsx
  src/pages/EmployeeManagement/ManageOrder/EmployeeOrderManagement/EmployeeManageOrderScreen/ManageOrderScreen.tsx
  src/pages/Order/AllTransactionHistory/AllTransactionHistoryComponent.tsx
  src/pages/Order/Components/ProgressBar/VerticalStepperComponent.tsx
  src/pages/Order/OrderDetail/OrderDetailScreen.tsx
  src/pages/Order/OrderHistory/OrderHistoryScreen.tsx
  src/pages/Order/OrderProduct/ChangeAddressDialogComponent.tsx
  src/pages/Order/RefundTransactionHistory/RefundTransactionHistoryScreen.tsx
  src/pages/Order/ReportHistory/ReportHistorySreen.tsx
Labels: fIX-bug, update, feature, reviewing

#129 Revert 65 feature fe0030 create manage process with role brand
  src/models/ManagerExpertTailoringModel.tsx
  src/models/ManagerSizeExpertTailoringModel.tsx
  src/pages/BrandManagement/GlobalComponent/WaitingProcess/WaitingProcessComponent.tsx
  src/pages/BrandManagement/ManagePrice/AddManualPrice/AddPriceScreens.tsx
  src/pages/EmployeeManagement/DashboardEmployee/DashboardEmployeeScreen.tsx
  src/pages/Home/HomeScreen.tsx
  src/pages/ManagerManagement/ExpertTailoring/AddEachWithHand/AddEachExpertTailoringWithHandScreens.tsx
  src/pages/ManagerManagement/ExpertTailoring/ManagerExpertTailoringManagement/ManagerEditExpertTailoring/EditExpertTailoringPopUpScreens.tsx
  src/pages/ManagerManagement/ExpertTailoring/ManagerExpertTailoringManagement/ManagerManageScreen/ManageExpertTailoringScreens.tsx
  src/pages/ManagerManagement/ExpertTailoringMaterial/ManagerExpertTailoringMaterialManagement/ManagerManageExpertTailoringMaterialScreen/ManageExpertTailoringMaterialScreens.tsx
  src/pages/ManagerManagement/SizeExpertTailoring/AddEachWithHand/AddEachSizeExpertTailoringWithHandScreens.tsx
  src/pages/ManagerManagement/SizeExpertTailoring/ManagerSizeExpertTailoringManagement/ManagerEditSizeExpertTailoring/EditSizeExpertTailoringPopUpScreens.tsx
  src/pages/ManagerManagement/SizeExpertTailoring/ManagerSizeExpertTailoringManagement/ManagerManageScreen/ManageExpertTailoringScreens.tsx
Labels: fIX-bug, update, feature, reviewing

#130 [FE0044] Update accountant interface
  src/components/Dialog/StatusInformationDialog/StatusInformationDialog.tsx
  src/pages/AccountantManagement/AccountantManagePaymentForBrand/AccountantManagePaymentForBrandComponent.tsx
  src/pages/BrandManagement/BrandUploadInfor/BrandUploadInforComponent.tsx
  src/pages/BrandManagement/ManageMaterial/DashboardManageMaterial/DashBoardManageMaterialComponent.tsx
  src/pages/BrandManagement/ManageOrder/BrandOrderManagement/ManageOrderScreen.tsx
  src/pages/Order/OrderDetail/OrderDetailScreen.tsx
Labels: create, update, feature, reviewing

#131 [FE0030] Update UI Of Brand Manage Productivity
  src/api/ApiConfig.tsx
  src/pages/BrandManagement/BrandProfile/BrandProfileComponent.tsx
  src/pages/BrandManagement/BrandProperty/ManageExpertailoring/BrandManageExpertTailoringComponent.tsx
  src/pages/BrandManagement/BrandProperty/ManageProperties/ManagePropertiesComponent.tsx
  src/pages/BrandManagement/GlobalComponent/Dialog/BrandProductivity/BrandProductivityInputDialog.tsx
  src/pages/BrandManagement/GlobalComponent/SideBarComponent/SideBarComponent.tsx
  src/pages/BrandManagement/ManageMaterial/DashboardManageMaterial/DashBoardManageMaterialComponent.tsx
Labels: fIX-bug, update, feature, reviewing

#132 [FE0044] Update interface
  src/pages/AccountantManagement/AccountantManagePaymentForBrand/AccountantManagePaymentForBrandComponent.tsx
  src/pages/BrandManagement/BrandUploadInfor/BrandUploadInforComponent.tsx
  src/pages/Home/HomeScreen.tsx
  src/pages/Order/OrderDetail/OrderDetailScreen.tsx
Labels: fIX-bug, update, feature, reviewing

#134 [FE0044] Update 3d viewmode
  src/components/Dialog/3DModelDialog/3DModelDialog.tsx
  src/components/Dialog/3DModelDialog/3DModelDialogStyle.module.scss
  src/components/Dialog/StatusInformationDialog/StatusInformationDialog.tsx
  src/components/Header/HeaderComponent.tsx
  src/components/Notification/NotificationComponent.tsx
  src/pages/AccountantManagement/GlobalComponent/NavbarComponent/NavbarComponent.tsx
  src/pages/AdminManagement/GlobalComponent/NavbarComponent/NavbarComponent.tsx
  src/pages/BrandManagement/BrandOrderManagement/PartOfDesignInformationDialogComponent.tsx
  src/pages/BrandManagement/GlobalComponent/Notification/NotificationBrandComponent.tsx
  src/pages/BrandManagement/ManageOrder/BrandOrderManagement/ManageOrderScreen.tsx
  src/pages/CustomDesign/CustomDesignScreen.tsx
  src/pages/CustomDesign/Designer/Designer.jsx
  src/pages/EmployeeManagement/GlobalComponent/NavBarComponent/NavbarComponent.tsx
  src/pages/EmployeeManagement/GlobalComponent/Notification/NotificationEmployeeComponent.tsx
  src/pages/EmployeeManagement/ManageOrder/EmployeeOrderManagement/EmployeeManageOrderScreen/ManageOrderScreen.tsx
  src/pages/ManagerManagement/GlobalComponent/NavBarComponent/NavbarComponent.tsx
  src/pages/Order/OrderDetail/OrderDetailScreen.tsx
  src/pages/Order/OrderHistory/OrderHistoryScreen.tsx
Labels: create, update, feature, reviewing

#135 [FE0030] Update Brand Sign Up
  src/pages/Authentication/SignIn/SignInScreen.tsx
  src/pages/BrandManagement/BrandAuth/SignUpBrand/BrandSignUpScreen.tsx
  src/pages/BrandManagement/BrandProperty/ManageExpertailoring/BrandManageExpertTailoringComponent.tsx
  src/pages/BrandManagement/BrandProperty/ManageProperties/ManagePropertiesComponent.tsx
  src/pages/BrandManagement/BrandUploadInfor/BrandUploadInforComponent.tsx
  src/pages/BrandManagement/GlobalComponent/NavBarComponent/NavbarComponent.tsx
  src/pages/BrandManagement/GlobalComponent/WaitingProcess/WaitingProcessComponent.tsx
  src/pages/BrandManagement/ManageMaterial/DashboardManageMaterial/DashBoardManageMaterialComponent.tsx
  src/pages/BrandManagement/ManagePrice/AddManualPrice/AddPriceScreens.tsx
  src/pages/BrandManagement/ManagePrice/BrandPriceManagement/BrandEditPrice/EditPricePopUpScreens.tsx
  src/pages/BrandManagement/ManagePrice/BrandPriceManagement/BrandManagementScreen/ManagePriceScreens.tsx
Labels: fIX-bug, update, feature, reviewing

#138 [FE0044] Update lable status
  src/pages/BrandManagement/ManageOrder/BrandOrderManagement/ManageOrderScreen.tsx
  src/pages/EmployeeManagement/ManageOrder/EmployeeOrderManagement/EmployeeManageOrderScreen/ManageOrderScreen.tsx
  src/pages/EmployeeManagement/ManageReport/EmployeeReportManagement/EmployeeManageReportScreen/ManageReportScreen.tsx
Labels: update, feature, reviewing

#139 [FE0044] Update interface
  src/components/Dialog/PolicyDialog/CancelOrderPolicyDialogComponent.tsx
  src/components/Dialog/PolicyDialog/OrderPolicyDialogComponent.tsx
  src/pages/AccountantManagement/AccountantManagePaymentForBrand/AccountantManagePaymentForBrandComponent.tsx
  src/pages/AdminManagement/ManagePrice/AdminPriceManagement/AdminManagementScreen/ManagePriceScreens.tsx
  src/pages/Order/Components/Dialog/PaymentInformationDialog/PaymentInformationDialogComponent.tsx
Labels: update, feature, reviewing

#140 [FE0044] Update interface
  src/assets/clothes/long_shirt.png
  src/assets/clothes/seleeve_hoodie.png
  src/canvas/LongSkirt.jsx
  src/components/Dialog/RefunctionRequestDialog/CreateRefundInformationDialogComponent.tsx
  src/models/DesignModel.tsx
  src/pages/AccountantManagement/GlobalComponent/NavbarComponent/NavbarComponent.tsx
  src/pages/AdminManagement/GlobalComponent/NavbarComponent/NavbarComponent.tsx
  src/pages/BrandManagement/BrandUploadInfor/BrandUploadInforComponent.tsx
  src/pages/BrandManagement/GlobalComponent/NavBarComponent/NavbarComponent.tsx
  src/pages/BrandManagement/ManageOrder/BrandOrderManagement/ManageOrderScreen.tsx
  src/pages/CustomDesign/CustomDesignScreen.tsx
  src/pages/EmployeeManagement/ManageOrder/EmployeeOrderManagement/EmployeeManageOrderScreen/ManageOrderScreen.tsx
  src/pages/ManagerManagement/GlobalComponent/NavBarComponent/NavbarComponent.tsx
  src/pages/Order/PickedOrder/PickedOrderScreen.tsx
Labels: update, feature, reviewing

#141 [FE0044] Update process
  src/pages/AccountantManagement/AccountantManagePaymentForBrand/AccountantManagePaymentForBrandComponent.tsx
  src/pages/AccountantManagement/AccountantManageRefundPayment/AccountantManageRefundPaymentForBrandComponent.tsx
  src/pages/BrandManagement/BrandUploadInfor/BrandUploadInforComponent.tsx
  src/pages/BrandManagement/ManageMaterial/CRUDMaterialWithExcelTable/AddMultipleInExcelTable/AddMultipleMaterialComponent.tsx
Labels: update, feature, reviewing
