Repository TTTM-Mavericks/smart-tailor-FE, pull requests merged in 2024-07, with the labels that each got.

#55 [FE0044] Update order processing detail
  package-lock.json
  package.json
  src/components/ChooseMaterialDialog/ChooseMaterialDialogComponent.tsx
  src/components/ChooseMaterialDialog/ChooseMaterialDialogStyle.module.scss
  src/components/CustomButton/CustomButton.jsx
  src/components/CustomButton/CustomButton.module.scss
  src/components/Dialog/PolicyDialog/CancelOrderPolicyDialogComponent.tsx
  src/components/Dialog/PolicyDialog/ChangeDesignPolicyDialogComponent.tsx
  src/components/Dialog/PolicyDialog/OrderPolicyDialogComponent.tsx
  src/components/Dialog/PolicyDialog/OrderPolicyDialogComponentStyle.module.scss
  src/components/Dialog/SizeDialog/SizeDialogComponent.tsx
  src/components/Dialog/SizeDialog/SizeDialogComponentStyle.module.scss
  src/components/Footer/FooterComponent.tsx
  src/components/Header/Header.module.scss
  src/components/Header/HeaderComponent.tsx
  src/components/ImageMasonry/ImageMasonryCoponent.tsx
  src/main.jsx
  src/models/DesignModel.tsx
  src/models/UserModel.tsx
  src/pages/AdminManagement/AdminProfile/AdminProfileSettingComponent.tsx
  src/pages/AdminManagement/ExpertTailoring/AddMultipleExpertTailoringWithExcel/AddMultipleExpertTailoringComponent.tsx
  src/pages/AdminManagement/ExpertTailoring/ManagerExpertTailoringManagement/ManagerEditExpertTailoring/EditExpertTailoringPopUpStyles.module.scss
  src/pages/AdminManagement/GlobalComponent/Notification/NotificationWithSocketIOComponent.tsx
  src/pages/AdminManagement/ManageCategory/AddMultipleCategoryWithExcel/AddMultipleMaterialComponent.tsx
  src/pages/AdminManagement/ManageCategory/AdminCategoryManagement/AdminEditMaterial/EditMaterialPopUpStyles.module.scss
  src/pages/AdminManagement/ManageInvoice/ManageInvoiceScreens.tsx
  src/pages/AdminManagement/ManageMaterials/AddMultipleMaterialWithExcel/AddMultipleMaterialComponent.tsx
  src/pages/AdminManagement/ManageMaterials/AdminMaterialManagerment/AdminEditMaterial/EditMaterialPopUpStyles.module.scss
  src/pages/Authentication/ProfileSetting/ProfileSettingScreen.tsx
  src/pages/Authentication/SignIn/SignInDialog.tsx
  src/pages/Authentication/SignIn/SignInScreen.tsx
  src/pages/BrandManagement/BrandProfile/BrandProfileComponent.tsx
  src/pages/BrandManagement/GlobalComponent/Notification/NotificationBrandComponent.tsx
  src/pages/BrandManagement/ManageMaterial/CRUDMaterialWithExcelTable/AddMultipleInExcelTable/AddMultipleMaterialComponent.tsx
  src/pages/BrandManagement/ManageMaterial/MaterialManage/EditMaterial/EditMaterialPopUpStyles.module.scss
  src/pages/CustomDesign/Components/Dialog/ProductDialogComponent.tsx
  src/pages/CustomDesign/Components/MaterialDetail/MaterialDetailComponent.tsx
  src/pages/CustomDesign/Components/MaterialDetail/MaterialDetailStyle.module.scss
  src/pages/CustomDesign/CustomDesign.module.scss
  src/pages/CustomDesign/CustomDesignScreen.tsx
  src/pages/EmployeeManagement/EmployeeProfile/EmployeeProfileComponent.tsx
  src/pages/EmployeeManagement/GlobalComponent/Notification/NotificationEmployeeComponent.tsx
  src/pages/EmployeeManagement/ManageBrand/EmployeeBrandManagement/EmployeeEditBrand/EditUserPopUpStyles.module.scss
  src/pages/EmployeeManagement/ManageCustomer/AddMultipleUserWithExcel/AddMultipleUsersComponent.tsx
  src/pages/EmployeeManagement/ManageCustomer/EditUserPopUpStyles.module.scss
  src/pages/EmployeeManagement/ManageOrder/EmployeeOrderManagement/EmployeeEditOrder/EditOrderPopUpStyles.module.scss
  src/pages/Home/HomeScreen.tsx
  src/pages/ManagerManagement/ExpertTailoring/ManagerExpertTailoringManagement/ManagerEditExpertTailoring/EditExpertTailoringPopUpStyles.module.scss
  src/pages/ManagerManagement/ManageBrand/ManagerBrandManagement/ManagerEditBrand/EditBrandPopUpStyles.module.scss
  src/pages/Order/Components/ProgressBar/VerticalStepperComponent.tsx
  src/pages/Order/Components/ProgressBar/VerticalStepperStyle.module.scss
  src/pages/Order/Components/Table/MaterialDetailTableComponent.tsx
  src/pages/Order/Components/Table/MaterialDetailTableComponentStyle.module.scss
  src/pages/Order/OrderDetail/OrderDetailScreen.tsx
  src/pages/Order/OrderDetail/OrderDetailStyles.module.scss
  src/pages/Order/OrderHistory/OrderHistoryScreen.tsx
  src/pages/Order/OrderProduct/ChangeAddressDialogComponent.tsx
  src/pages/Order/OrderProduct/OrderProductScreen.tsx
  src/pages/Order/OrderProduct/OrderProductStyle.module.scss
Labels: create, update, feature, reviewing

#56 [FE0044] Update order request screen for brand
  src/App.jsx
  src/components/Dialog/PolicyDialog/CancelOrderPolicyDialogComponent.tsx
  src/components/Dialog/PolicyDialog/ChangeDesignPolicyDialogComponent.tsx
  src/components/Dialog/PolicyDialog/OrderPolicyDialogComponent.tsx
  src/index.module.scss
  src/models/DesignModel.tsx
  src/models/OrderModel.tsx
  src/pages/Authentication/ProfileSetting/ProfileSettingScreen.tsx
  src/pages/BrandManagement/BrandOrderManagement/OrderRequestDetailsComponent.tsx
  src/pages/BrandManagement/BrandOrderManagement/OrderRequestScreen.tsx
  src/pages/BrandManagement/BrandOrderManagement/OrderRequestStyle.module.scss
  src/pages/BrandManagement/BrandOrderManagement/PartOfDesignInformationDialogComponent.tsx
  src/pages/BrandManagement/GlobalComponent/SideBarComponent/SideBarComponent.tsx
  src/pages/BrandManagement/index.tsx
  src/pages/Order/Components/Dialog/PaymentInformationDialog/PaymentInformationDialogComponent.tsx
  src/pages/Order/Components/Dialog/PaymentInformationDialog/PaymentInformationDialogStyle.module.scss
  src/pages/Order/OrderDetail/OrderDetailScreen.tsx
  src/pages/Order/OrderDetail/OrderDetailStyles.module.scss
  src/pages/Order/OrderHistory/OrderHistoryScreen.tsx
  src/pages/Order/OrderHistory/OrderHistoryStyles.module.scss
Labels: create, update, feature, reviewing

#57 [FE0040] Update create design screen
  src/App.jsx
  src/api/ApiConfig.tsx
  src/components/Card/ProductCard/ProductCard.tsx
  src/components/Card/ProductCard/ProductCardStyle.module.scss
  src/components/ChooseMaterialDialog/ChooseMaterialDialogComponent.tsx
  src/components/Dialog/PolicyDialog/OrderPolicyDialogComponent.tsx
  src/models/DesignModel.tsx
  src/models/OrderModel.tsx
  src/pages/Authentication/SignIn/SignInScreen.tsx
  src/pages/BrandManagement/BrandOrderManagement/OrderRequestDetailsComponent.tsx
  src/pages/BrandManagement/BrandOrderManagement/PartOfDesignInformationDialogComponent.tsx
  src/pages/CustomDesign/Components/Dialog/ProductDialogComponent.tsx
  src/pages/CustomDesign/Components/Dialog/ProductDialogStyle.module.scss
  src/pages/CustomDesign/Components/Draggable/ImageDraggableComponent.tsx
  src/pages/CustomDesign/Components/MaterialDetail/MaterialDetailComponent.tsx
  src/pages/CustomDesign/Components/OptionFilter/OptionFilterCompnentDialog.tsx
  src/pages/CustomDesign/Components/OptionFilter/OptionFilterDialogStyle.module.scss
  src/pages/CustomDesign/CustomDesignScreen.tsx
  src/pages/Order/OrderDetail/OrderDetailScreen.tsx
  src/pages/Order/OrderDetail/OrderDetailStyles.module.scss
  src/pages/Order/OrderProduct/OrderProductScreen.tsx
  src/utils/DesignerUtils.js
Labels: fIX-bug, create, update, feature, reviewing

#60 [FE0030] Fix Bugs Of Brand Add Excel Can Be Null In Brand Price
  src/pages/BrandManagement/ManageMaterial/CRUDMaterialWithExcelTable/AddMultipleInExcelTable/AddMultipleMaterialComponent.tsx
  src/pages/BrandManagement/ManageMaterial/MaterialManage/EditMaterial/EditMaterialPopUpScreens.tsx
  src/pages/BrandManagement/ManageMaterial/MaterialManage/MaterialManageScreens.tsx
Labels: fIX-bug, reviewing

#61 [FE0040] Update design and order screen
  package-lock.json
  package.json
  src/App.jsx
  src/api/ApiConfig.tsx
  src/models/DesignModel.tsx
  src/models/OrderModel.tsx
  src/pages/BrandManagement/BrandOrderManagement/OrderRequestDetailsComponent.tsx
  src/pages/BrandManagement/BrandOrderManagement/OrderRequestScreen.tsx
  src/pages/CustomDesign/Components/Dialog/ProductDialogComponent.tsx
  src/pages/CustomDesign/Components/ItemEditorTools/ItemEditorToolsComponent.tsx
  src/pages/CustomDesign/Components/ItemEditorTools/ItemEditorToolsStyle.module.scss
  src/pages/CustomDesign/Components/MaterialDetail/MaterialDetailComponent.tsx
  src/pages/CustomDesign/CustomDesign.module.scss
  src/pages/CustomDesign/CustomDesignScreen.tsx
  src/pages/Order/Components/ProgressBar/VerticalStepperComponent.tsx
  src/pages/Order/Components/Table/MaterialDetailTableComponent.tsx
  src/pages/Order/OrderDetail/OrderDetailScreen.tsx
  src/pages/Order/OrderProduct/ChangeAddressDialogComponent.tsx
  src/pages/Order/OrderProduct/OrderProductScreen.tsx
  src/utils/NumbericUtils.tsx
Labels: fIX-bug, update, feature, reviewing

#62 [FE0040] Update success img url
  package-lock.json
  package.json
  src/components/Header/HeaderComponent.tsx
  src/models/DesignModel.tsx
  src/models/OrderModel.tsx
  src/pages/AdminManagement/DashboardAdmin/DashboardAdminScreens.tsx
  src/pages/Authentication/ProfileSetting/ProfileSettingScreen.tsx
  src/pages/BrandManagement/BrandOrderManagement/OrderRequestDetailsComponent.tsx
  src/pages/BrandManagement/BrandOrderManagement/PartOfDesignInformationDialogComponent.tsx
  src/pages/CustomDesign/Components/Draggable/ImageDraggableComponent.tsx
  src/pages/CustomDesign/CustomDesignScreen.tsx
  src/pages/DetailProduct/ProductDetail/ProductDetailScreens.tsx
  src/pages/FilterProduct/ProductFilterScreen/FilterProductScreen.tsx
  src/pages/Order/Components/Table/MaterialDetailTableComponent.tsx
  src/pages/Order/OrderProduct/OrderProductScreen.tsx
  src/utils/CanvasUtils.tsx
Labels: fIX-bug, update, feature, reviewing

#66 Revert "[FE0030] Create Upload Brand Information Page "
  src/App.jsx
  src/api/ApiConfig.tsx
  src/models/AdminCategoryExcelModel.tsx
  src/models/AdminMaterialExcelModel.tsx
  src/models/BrandUploadInforModel.tsx
  src/models/ManagerBrandModel.tsx
  src/pages/AdminManagement/ManageCategory/AddEachWithHand/AddEachCategoryWithHandScreens.tsx
  src/pages/AdminManagement/ManageCategory/AdminCategoryManagement/AdminManagerScreen/ManageCategoryScreens.tsx
  src/pages/AdminManagement/ManageMaterials/AddMultipleMaterialWithExcel/AddMultipleMaterialComponent.tsx
  src/pages/AdminManagement/ManageSize/AdminSizeManagement/AdminManagerScreen/ManageSizeScreens.tsx
  src/pages/Authentication/SignIn/SignInScreen.tsx
  src/pages/BrandManagement/BrandUploadInfor/BrandUploadInforComponent.tsx
  src/pages/BrandManagement/BrandUploadInfor/DashboardBrandUploadInformationComponent.tsx
  src/pages/BrandManagement/GlobalComponent/SideBarComponent/SideBarComponent.tsx
  src/pages/BrandManagement/GlobalComponent/VerticalStepProgress/VerticalStepProgressComponent.tsx
  src/pages/BrandManagement/GlobalComponent/WaitingProcess/WaitingProcessComponent.tsx
  src/pages/BrandManagement/ManageMaterial/AddEachWithHand/AddEachMaterialWithHandScreens.tsx
  src/pages/BrandManagement/ManageMaterial/CRUDMaterialWithExcelTable/AddMultipleInExcelTable/AddMultipleMaterialComponent.tsx
  src/pages/BrandManagement/ManageMaterial/DashboardManageMaterial/DashBoardManageMaterialComponent.tsx
  src/pages/BrandManagement/ManageMaterial/MaterialManage/EditMaterial/EditMaterialPopUpScreens.tsx
  src/pages/BrandManagement/ManageMaterial/MaterialManage/MaterialManageScreens.tsx
  src/pages/BrandManagement/index.tsx
  src/pages/ManagerManagement/ExpertTailoring/AddMultipleExpertTailoringWithExcel/AddMultipleExpertTailoringComponent.tsx
  src/pages/ManagerManagement/ExpertTailoring/DashboardManagerExpertTailoring/DashBoardManageExpertTailoringComponent.tsx
  src/pages/ManagerManagement/ManageBrand/ManagerBrandManagement/ManagerManageBrandScreen/ManageBrandScreens.tsx
Labels: reject

#69 [FE0030] Fix Bugs UI
  src/api/ApiConfig.tsx
  src/pages/AdminManagement/ManageMaterials/AddMultipleMaterialWithExcel/AddMultipleMaterialComponent.tsx
  src/pages/Authentication/SignIn/SignInScreen.tsx
  src/pages/BrandManagement/BrandAuth/SignUpBrand/BrandSignUpScreen.tsx
  src/pages/BrandManagement/BrandAuth/SignUpBrand/BrandSignUpStyle.module.scss
  src/pages/BrandManagement/BrandUploadInfor/BrandUploadInforComponent.tsx
  src/pages/ManagerManagement/ManageBrand/ManagerBrandManagement/ManagerManageBrandScreen/ManageBrandScreens.tsx
Labels: fIX-bug, update, feature, reviewing

#70 [FE0044] Update order report detail
  package-lock.json
  package.json
  src/canvas/Shirt.jsx
  src/components/ChooseMaterialDialog/ChooseMaterialDialogComponent.tsx
  src/components/Dialog/PaymentDialog/PaymentOrderDialogComponent.tsx
  src/components/Dialog/ReportDialog/CustomerReportOrderDialogComponent.tsx
  src/components/Dialog/ReportDialog/CustomerReportOrderDialogComponentStyle.module.scss
  src/components/Loading/LoadingStyle.module.scss
  src/components/index.js
  src/models/OrderModel.tsx
  src/models/PaymentModel.tsx
  src/pages/BrandManagement/BrandOrderManagement/OrderRequestDetailsComponent.tsx
  src/pages/BrandManagement/BrandOrderManagement/OrderRequestScreen.tsx
  src/pages/CustomDesign/Components/MaterialDetail/MaterialDetailComponent.tsx
  src/pages/CustomDesign/Components/MaterialDetail/MaterialDetailStyle.module.scss
  src/pages/CustomDesign/CustomDesignScreen.tsx
  src/pages/FilterProduct/ProductFilterScreen/FilterProductScreen.tsx
  src/pages/Order/Components/Dialog/PaymentInformationDialog/PaymentInformationDialogComponent.tsx
  src/pages/Order/Components/ProgressBar/VerticalStepperComponent.tsx
  src/pages/Order/OrderDetail/OrderDetailScreen.tsx
  src/pages/Order/OrderHistory/OrderHistoryScreen.tsx
  src/pages/Order/OrderProduct/ChangeAddressDialogComponent.tsx
  src/pages/Order/OrderProduct/OrderProductScreen.tsx
Labels: update, feature, reviewing

#71 [FE0044] Update order processing detail
  src/App.jsx
  src/api/ApiConfig.tsx
  src/components/Dialog/ReportDialog/CustomerReportOrderDialogComponent.tsx
  src/components/Header/HeaderComponent.tsx
  src/models/DesignModel.tsx
  src/pages/CustomDesign/Components/CreateDesign/CreateDesignComponent.tsx
  src/pages/CustomDesign/Components/MaterialDetail/MaterialDetailComponent.tsx
  src/pages/CustomDesign/CustomDesign.module.scss
  src/pages/CustomDesign/CustomDesignScreen.tsx
  src/pages/DesignCollection/DesignCollectionContainer/DesignCollectionScreen.tsx
  src/pages/DesignCollection/DesignCollectionContainer/DesignCollectionStyle.module.scss
  src/pages/Order/OrderDetail/OrderDetailScreen.tsx
  src/pages/Order/OrderDetail/OrderDetailStyles.module.scss
  src/pages/Order/OrderHistory/OrderHistoryScreen.tsx
Labels: fIX-bug, update, feature, reviewing

#72 [FE0044] Update model rotate
  src/canvas/Shirt.jsx
  src/pages/CustomDesign/Components/Draggable/ImageDraggableComponent.tsx
  src/pages/CustomDesign/Components/ItemEditorTools/ItemEditorToolsComponent.tsx
  src/pages/CustomDesign/CustomDesignScreen.tsx
Labels: fIX-bug, create, update, reviewing

#73 [FE0044] Update order detail screen and add props for design model
  src/api/ApiConfig.tsx
  src/canvas/Shirt.jsx
  src/components/ChooseMaterialDialog/ChooseMaterialDialogComponent.tsx
  src/models/DesignModel.tsx
  src/pages/BrandManagement/BrandOrderProcessing/BrandManageOrderProcessingComponent.tsx
  src/pages/BrandManagement/BrandOrderProcessing/BrandManageOrderProcessingComponentStyle.module.scss
  src/pages/BrandManagement/GlobalComponent/SideBarComponent/SideBarComponent.tsx
  src/pages/BrandManagement/ManageMaterial/DashboardManageMaterial/DashBoardManageMaterialComponent.tsx
  src/pages/BrandManagement/index.tsx
  src/pages/CustomDesign/Components/CreateDesign/CreateDesignComponent.tsx
  src/pages/CustomDesign/Components/Draggable/ImageDraggableComponent.tsx
  src/pages/CustomDesign/Components/ItemEditorTools/ItemEditorToolsComponent.tsx
  src/pages/CustomDesign/Components/MaterialDetail/MaterialDetailComponent.tsx
  src/pages/CustomDesign/CustomDesignScreen.tsx
  src/pages/Order/Components/ProgressBar/VerticalStepperComponent.tsx
  src/pages/Order/OrderDetail/OrderDetailScreen.tsx
  src/pages/Order/OrderHistory/OrderHistoryScreen.tsx
Labels: fIX-bug, create, update, feature, reviewing

#74 [FE0044] Update payment process
  src/api/ApiConfig.tsx
  src/components/Dialog/PaymentDialog/PaymentOrderDialogComponent.tsx
  src/components/Dialog/ReportDialog/CustomerReportOrderDialogComponent.tsx
  src/models/PaymentModel.tsx
  src/pages/BrandManagement/BrandOrderProcessing/BrandManageOrderProcessingComponent.tsx
  src/pages/Order/Components/ProgressBar/VerticalStepperComponent.tsx
  src/pages/Order/OrderDetail/OrderDetailScreen.tsx
  src/pages/Order/OrderHistory/OrderHistoryScreen.tsx
  src/pages/Order/OrderHistory/OrderHistoryStyles.module.scss
Labels: fIX-bug, update, feature, reviewing

#75 [FE0030] Revert 65 feature fe0030 create manage process with role brand
  package-lock.json
  package.json
  src/App.jsx
  src/api/ApiConfig.tsx
  src/components/ImageMasonry/ImageMasonryCoponent.tsx
  src/main.jsx
  src/models/BrandManageOrderModel.tsx
  src/models/BrandUploadInforModel.tsx
  src/models/EmployeeManageOrderModel.tsx
  src/models/EmployeeManageReportModel.tsx
  src/models/ManagerBrandModel.tsx
  src/pages/AccountantManagement/AccountantDashboard/AccountantDashboardScreen.tsx
  src/pages/AccountantManagement/DashboardAccountant/DashboardAccountantScreens.tsx
  src/pages/AccountantManagement/GlobalComponent/Card/CardComponent.module.scss
  src/pages/AccountantManagement/GlobalComponent/Card/CardComponent.tsx
  src/pages/AccountantManagement/GlobalComponent/CustomToolBar/CustomToolBar.tsx
  src/pages/AccountantManagement/GlobalComponent/Error404/Error404Component.tsx
  src/pages/AccountantManagement/GlobalComponent/Error404/Error404Styles.module.scss
  src/pages/AccountantManagement/GlobalComponent/LanguageSetting/LanguageSettingComponent.tsx
  src/pages/AccountantManagement/GlobalComponent/LanguageSetting/LanguageSettingStyles.module.scss
  src/pages/AccountantManagement/GlobalComponent/NavbarComponent/NavbarComponent.tsx
  src/pages/AccountantManagement/GlobalComponent/Notification/NotificationComponent.tsx
  src/pages/AccountantManagement/GlobalComponent/Notification/NotificationStyles.module.scss
  src/pages/AccountantManagement/GlobalComponent/Notification/NotificationWithSocketIOComponent.tsx
  src/pages/AccountantManagement/GlobalComponent/ProgressCircle/ProgressCircle.module.scss
  src/pages/AccountantManagement/GlobalComponent/ProgressCircle/ProgressCircleComponent.tsx
  src/pages/AccountantManagement/GlobalComponent/SidebarComponent/SidebarComponent.tsx
  src/pages/AccountantManagement/GlobalComponent/TopBar/TopBarComponent.tsx
  src/pages/AccountantManagement/GlobalComponent/TopBar/TopBarStyle.module.scss
  src/pages/AccountantManagement/ManageRefund/ManageRefundScreen.tsx
  src/pages/AccountantManagement/index.tsx
  src/pages/AdminManagement/DashboardAdmin/DashboardAdminScreens.tsx
  src/pages/AdminManagement/GlobalComponent/SidebarComponent/SidebarComponent.tsx
  src/pages/AdminManagement/ManageCategory/AddEachWithHand/AddEachCategoryWithHandScreens.tsx
  src/pages/AdminManagement/ManageMaterials/AddMultipleMaterialWithExcel/AddMultipleMaterialComponent.tsx
  src/pages/AdminManagement/ManageMaterials/AdminMaterialManagerment/AdminManagerScreen/ManageMaterialScreens.tsx
  src/pages/AdminManagement/SystemConfigurationAdministration/SystemConfigurationAdministrationScreen.tsx
  src/pages/Authentication/SignIn/SignInScreen.tsx
  src/pages/BrandManagement/BrandOrderManagement/OrderRequestDetailsComponent.tsx
  src/pages/BrandManagement/BrandProfile/BrandProfileComponent.tsx
  src/pages/BrandManagement/BrandUploadInfor/BrandUploadInforComponent.tsx
  src/pages/BrandManagement/GlobalComponent/NavBarComponent/NavbarComponent.tsx
  src/pages/BrandManagement/GlobalComponent/Notification/NotificationBrandComponent.tsx
  src/pages/BrandManagement/GlobalComponent/Notification/NotificationComponent.jsx
  src/pages/BrandManagement/GlobalComponent/SideBarComponent/SideBarComponent.tsx
  src/pages/BrandManagement/ManageMaterial/CRUDMaterialWithExcelTable/AddMultipleInExcelTable/AddMultipleMaterialComponent.tsx
  src/pages/BrandManagement/ManageMaterial/DashboardManageMaterial/DashBoardManageMaterialComponent.tsx
  src/pages/BrandManagement/ManageNotification/NotificationPageComponent.tsx
  src/pages/BrandManagement/ManageOrder/BrandOrderManagement/ManageOrderScreen.tsx
  src/pages/EmployeeManagement/DashboardEmployee/DashboardEmployeeScreen.tsx
  src/pages/EmployeeManagement/ManageBrand/EmployeeBrandManagement/EmployeeManageBrandScreen/ManageBrandScreen.tsx
  src/pages/EmployeeManagement/ManageOrder/EmployeeOrderManagement/EmployeeManageOrderScreen/ManageOrderScreen.tsx
  src/pages/EmployeeManagement/ManageReport/EmployeeReportManagement/EmployeeManageReportScreen/ManageReportScreen.tsx
  src/pages/EmployeeManagement/ManageReport/EmployeeReportManagement/EmployeeManageReportScreen/ManageReportStyles.module.scss
  src/pages/EmployeeManagement/ManageReport/EmployeeReportManagement/EmployeeManageReportScreen/testdata.json
  src/pages/FilterProduct/ProductFilterScreen/FilterProductScreen.tsx
  src/pages/FilterProduct/ProductFilterScreen/FilterProductStyles.scss
  src/pages/ManagerManagement/ManageBrand/ManagerBrandManagement/ManagerManageBrandScreen/ManageBrandScreens.tsx
  vite.config.js
Labels: fIX-bug, update, feature, reviewing

#76 [FE0030] Update Bug In UI Of Brand
  src/App.jsx
  src/pages/AccountantManagement/GlobalComponent/Toogle/ToogleComponent.tsx
  src/pages/AccountantManagement/GlobalComponent/Toogle/ToogleStyle.css
  src/pages/AdminManagement/ManageMaterials/AddMultipleMaterialWithExcel/AddMultipleMaterialComponent.tsx
  src/pages/BrandManagement/ManageOrder/BrandOrderManagement/ManageOrderScreen.tsx
  src/pages/EmployeeManagement/ManageOrder/EmployeeOrderManagement/EmployeeManageOrderScreen/ManageOrderScreen.tsx
Labels: fIX-bug, update, reviewing

#77 [FE0044] update brand order process
  src/api/ApiConfig.tsx
  src/assets/clothes/shirt-sleeve.png
  src/assets/index.js
  src/components/Dialog/ReportDialog/CustomerReportOrderDialogComponent.tsx
  src/pages/AccountantManagement/AccountantManagePaymentForBrand/AccountantManagePaymentForBrandComponent.tsx
  src/pages/AccountantManagement/AccountantManagePaymentForBrand/AccountantManagePaymentForBrandComponentStyle.module.scss
  src/pages/AccountantManagement/DashboardAccountant/DashboardAccountantScreens.tsx
  src/pages/BrandManagement/BrandOrderManagement/OrderRequestDetailsComponent.tsx
  src/pages/BrandManagement/BrandOrderManagement/OrderRequestScreen.tsx
  src/pages/BrandManagement/BrandOrderProcessing/BrandManageOrderProcessingComponent.tsx
  src/pages/BrandManagement/GlobalComponent/Dialog/BrandProductivity/BrandProductivityInputDialog.tsx
  src/pages/BrandManagement/GlobalComponent/Dialog/BrandProductivity/BrandProductivityInputDialogStyle.module.scss
  src/pages/BrandManagement/GlobalComponent/Dialog/UpdateSampleProduct/BrandUpdateSampleProductDialog.tsx
  src/pages/BrandManagement/GlobalComponent/Dialog/UpdateSampleProduct/BrandUpdateSampleProductDialogStyle.module.scss
  src/pages/BrandManagement/ManageOrder/BrandOrderManagement/ManageOrderScreen.tsx
  src/pages/CustomDesign/Components/CreateDesign/CreateDesignComponent.tsx
  src/pages/Order/Components/ProgressBar/VerticalStepperComponent.tsx
  src/pages/Order/OrderDetail/OrderDetailScreen.tsx
  src/pages/Order/OrderProduct/OrderProductScreen.tsx
Labels: fIX-bug, update, feature, reviewing
