Repository TTTM-Mavericks/smart-tailor-FE, pull requests merged in 2024-05, with the labels that each got.

#17 Feature fe0016 create contact us screen
  src/App.jsx
  src/pages/AboutUs/AboutUsComponent.tsx
  src/pages/AboutUs/AboutUsContent.tsx
  src/pages/AboutUs/AboutUsScreen.tsx
  src/pages/AboutUs/AboutUsScreens.tsx
  src/pages/AboutUs/AboutUsStyles.css
  src/pages/AboutUs/AboutUsVerticalCarouselComponent.tsx
  src/pages/AboutUs/CarouselStyles.css
  src/pages/AboutUs/CarouselStyles.module.scss
  src/pages/AboutUs/HeaderAboutUsComponent.tsx
  src/pages/AboutUs/TestAboutUs.tsx
  src/pages/AdminManagement/BarChart/BarChartScreens.tsx
  src/pages/AdminManagement/BarChart/DataTestBarChart.tsx
  src/pages/AdminManagement/CardInformationDetail/CardInformationDetail.module.scss
  src/pages/AdminManagement/CardInformationDetail/CardInformationDetailComponent.tsx
  src/pages/AdminManagement/DashboardAdmin/DashboardAdminScreens.tsx
  src/pages/AdminManagement/DashboardAdmin/DashboardAdminStyle.module.scss
  src/pages/AdminManagement/GeographyChart/DataTestGeographyChart.tsx
  src/pages/AdminManagement/GeographyChart/GeographyChartComponent.tsx
  src/pages/AdminManagement/GeographyChart/GeographyChartScreens.tsx
  src/pages/AdminManagement/GlobalComponent/Card/CardComponent.module.scss
  src/pages/AdminManagement/GlobalComponent/Card/CardComponent.tsx
  src/pages/AdminManagement/GlobalComponent/Notification/NotificationComponent.tsx
  src/pages/AdminManagement/GlobalComponent/ProgressCircle/ProgressCircle.module.scss
  src/pages/AdminManagement/GlobalComponent/ProgressCircle/ProgressCircleComponent.tsx
  src/pages/AdminManagement/GlobalComponent/SideBar/SideBarComponent.tsx
  src/pages/AdminManagement/GlobalComponent/TopBar/TopBarComponent.tsx
  src/pages/AdminManagement/LineChart/LineChartComponent.tsx
  src/pages/AdminManagement/LineChart/LineChartScreens.tsx
  src/pages/AdminManagement/ManageUsers/AddEachWithHand/AddEachUsersWithHandScreens.tsx
  src/pages/AdminManagement/ManageUsers/AddMultipleUserWithExcel/AddMultipleUsersComponent.tsx
  src/pages/AdminManagement/ManageUsers/DashBoardManageUserComponent.tsx
  src/pages/AdminManagement/ManageUsers/DashBoardUserStyle.module.scss
  src/pages/AdminManagement/ManageUsers/EditUsersPopUpScreens.tsx
  src/pages/AdminManagement/ManageUsers/ManageUsersScreens.tsx
  src/pages/AdminManagement/PieChart/PieChartScreens.tsx
  src/pages/AdminManagement/RecentTransaction/DashboardRecentTransactionComponent.tsx
  src/pages/AdminManagement/RecentTransaction/DashboardRecentTransactionStyle.module.scss
  src/pages/AdminManagement/RecentTransaction/RecentTransactionComponent.tsx
  src/pages/AdminManagement/RecentTransaction/RecentTransactionStyles.module.scss
  src/pages/ContactUs/ContactUsScreen.tsx
  src/pages/ContactUs/ContactUsStyles.module.scss
Labels: fIX-bug, merged, create, feature, reviewing

#21 [FE0005-0006] Create signin screen
  package-lock.json
  package.json
  src/api/ApiConfig.js
  src/assets/index.js
  src/components/Footer/FooterComponent.tsx
  src/components/Header/Header.module.scss
  src/components/Header/HeaderComponent.tsx
  src/index.module.scss
  src/pages/Authentication/SignIn/SignInScreens.tsx
  src/pages/Authentication/SignIn/SignInStyle.module.scss
  src/pages/Authentication/SignUp/SignUpScreen.tsx
  src/pages/ContactUs/ContactUsScreen.tsx
  src/pages/CustomDesign/CustomDesignScreen.tsx
  src/pages/Home/HomeScreen.tsx
  vite.config.js
  wrangler.toml
Labels: create, update, feature, reviewing

#24 [FE0041] Apply react i18next translation
  package-lock.json
  package.json
  src/assets/index.js
  src/assets/system/language.png
  src/assets/system/usa_flag.png
  src/assets/system/vietnam_flag.png
  src/components/Header/HeaderComponent.tsx
  src/i18n.js
  src/i18n/en.json
  src/i18n/vi.json
  src/index.css
  src/main.jsx
  src/pages/Authentication/SignIn/SignInScreens.tsx
  src/pages/Authentication/SignIn/SignInStyle.module.scss
  src/pages/Authentication/SignUp/SignUpScreens.tsx
  src/pages/Authentication/SignUp/SignUpStyle.module.scss
Labels: create, feature, reviewing

#28 [FE0040] Update interface of design screen
  public/shirt_baked1.glb
  public/shirt_with_long_sleeves.glb
  public/skirt_9.glb
  src/canvas/example.tsx
  src/components/ColorPicker/ColorPicker.module.scss
  src/components/Draggable/ImageDraggableComponent.tsx
  src/components/Draggable/ImageDraggableStyle.module.scss
  src/components/FilePicker/FilePicker.module.scss
  src/i18n/en.json
  src/i18n/vi.json
  src/index.module.scss
  src/pages/Authentication/SignIn/SignInScreens.tsx
  src/pages/CustomDesign/CustomDesign.module.scss
  src/pages/CustomDesign/CustomDesignScreen.tsx
  src/pages/CustomDesign/Designer/Designer.module.scss
  src/root/ColorSystem.tsx
Labels: fIX-bug, update, reviewing

#29 [FE0040] Update interface of design screen
  src/assets/clothes/front.png
  src/assets/index.js
  src/components/ColorPicker/ColorPicker.jsx
  src/components/ColorPicker/ColorPicker.module.scss
  src/components/CustomButton/CustomButton.jsx
  src/components/CustomButton/CustomButton.module.scss
  src/components/FilePicker/FilePicker.jsx
  src/components/FilePicker/FilePicker.module.scss
  src/i18n/en.json
  src/i18n/vi.json
  src/models/UltilModel.tsx
  src/pages/CustomDesign/CustomDesign.module.scss
  src/pages/CustomDesign/CustomDesignScreen.tsx
  src/pages/CustomDesign/Designer/Designer.jsx
  src/utils/DesignerUtils.js
Labels: fIX-bug, update, reviewing

#32 [FE0014] Create header and footer
  src/components/Header/HeaderComponent.tsx
  src/components/LanguageSetting/LanguageSettingComponent.tsx
  src/components/LanguageSetting/LanguageSettingStyles.module.scss
  src/i18n/en.json
  src/i18n/vi.json
  src/pages/AdminManagement/GlobalComponent/TopBar/TopBarComponent.tsx
Labels: update, feature, reviewing

#34 [FE0040] Update design screen with gllb model
  package-lock.json
  package.json
  src/canvas/CanvasModel.jsx
  src/canvas/Hoodie.jsx
  src/canvas/LongSkirt.jsx
  src/canvas/Shirt.jsx
  src/components/Draggable/ImageDraggableStyle.module.scss
  src/components/OptionFilter/OptionFilterCompnent.tsx
  src/components/OptionFilter/OptionFilterStyle.module.scss
  src/index.module.scss
  src/models/DesignModel.tsx
  src/models/ProductModel.tsx
  src/pages/CustomDesign/Components/Dialog/ProductDialogComponent.tsx
  src/pages/CustomDesign/Components/Dialog/ProductDialogStyle.module.scss
  src/pages/CustomDesign/Components/Draggable/ImageDraggableComponent.tsx
  src/pages/CustomDesign/Components/Draggable/ImageDraggableStyle.module.scss
  src/pages/CustomDesign/CustomDesign.module.scss
  src/pages/CustomDesign/CustomDesignScreen.tsx
  src/root/ColorSystem.tsx
Labels: create, update, feature

#37 [FE0011] Create home screen
  src/components/Footer/FooterComponent.tsx
  src/components/Header/HeaderComponent.tsx
  src/i18n/en.json
  src/i18n/vi.json
  src/pages/AboutUs/AboutUsScreen.tsx
  src/pages/AdminManagement/CardInformationDetail/CardInformationDetailComponent.tsx
  src/pages/AdminManagement/CardInformationDetail/CardinformationScreen.tsx
  src/pages/AdminManagement/DashboardAdmin/DashboardAdminScreens.tsx
  src/pages/AdminManagement/DashboardAdmin/DashboardAdminStyle.module.scss
  src/pages/AdminManagement/GlobalComponent/SideBar/SideBarComponent.tsx
  src/pages/AdminManagement/GlobalComponent/TopBar/TopBarComponent.tsx
  src/pages/AdminManagement/LineChart/LineChartScreens.tsx
  src/pages/EmployeeManagement/GlobalComponent/SideBar/SideBarEmployeeComponent.tsx
  src/pages/EmployeeManagement/GlobalComponent/TopBar/TopBarEmployeeComponent.tsx
  src/pages/EmployeeManagement/ManageNotification/ManageNotificationScreens.tsx
  src/pages/EmployeeManagement/ManageOrder/OrderDetailInformationComponent/RowDetailsComponent.tsx
  src/pages/Home/Home.module.scss
  src/pages/Home/HomeScreen.tsx
Labels: fIX-bug, update, reviewing
