Repository TTTM-Mavericks/smart-tailor-FE, pull requests merged in 2024-06, with the labels that each got.

#39 [FE0012] Create detail product screen
  src/App.jsx
  src/pages/AdminManagement/GlobalComponent/Notification/NotificationWithSocketIOComponent.tsx
  src/pages/BrandManagement/GlobalComponent/Notification/NotificationBrandComponent.tsx
  src/pages/BrandManagement/ManageNotification/DashboardManageNotificationComponent.tsx
  src/pages/BrandManagement/ManageNotification/ManageNotificationScreens.tsx
  src/pages/DetailProduct/ProductDetail/ProductDetailScreens.tsx
  src/pages/DetailProduct/ProductDetail/ProductDetailStyles.module.scss
  src/pages/DetailProduct/ReviewProduct/ReviewProductScreen.tsx
  src/pages/DetailProduct/ReviewProduct/ReviewProductStyles.module.scss
  src/pages/DetailProduct/index.tsx
  src/pages/EmployeeManagement/GlobalComponent/Notification/NotificationEmployeeComponent.tsx
  src/pages/EmployeeManagement/ManageNotification/ManageNotificationScreens.tsx
Labels: create, feature, reviewing

#40 [FE0007] Update signin state variable
  src/api/ApiConfig.tsx
  src/pages/Authentication/ForgotpassWord/ForgotPassWordScreen.tsx
  src/pages/Authentication/SignUp/SignUpScreen.tsx
  src/pages/CustomDesign/CustomDesignScreen.tsx
  src/pages/CustomDesign/Designer/Designer.jsx
Labels: fIX-bug, update, reviewing

#41 [FE0013] Create filter products screen
  src/App.jsx
  src/components/Header/HeaderComponent.tsx
  src/pages/BrandManagement/GlobalComponent/SideBar/SideBarBrandComponent.tsx
  src/pages/BrandManagement/ManageMaterial/AddEachWithHand/AddEachMaterialWithHandScreens.tsx
  src/pages/BrandManagement/ManageMaterial/AddEachWithHand/AddEachMaterialWithHandStyles.module.scss
  src/pages/BrandManagement/ManageMaterial/CRUDMaterialWithExcelTable/AddMaterialInExcelTable/AddMaterialInExcelTable.tsx
  src/pages/BrandManagement/ManageMaterial/CRUDMaterialWithExcelTable/AddMultipleInExcelTable/AddMultipleMaterialComponent.tsx
  src/pages/BrandManagement/ManageMaterial/CRUDMaterialWithExcelTable/AddMultipleInExcelTable/AddMultipleMaterialStyles.module.scss
  src/pages/BrandManagement/ManageMaterial/CRUDMaterialWithExcelTable/EditMaterialInExcelTable/EditMultipleUsersInExcelTable.tsx
  src/pages/BrandManagement/ManageMaterial/CRUDMaterialWithExcelTable/EditMaterialInExcelTable/EditMultipleUsersInExcelTableStyles.module.scss
  src/pages/BrandManagement/ManageMaterial/DashboardManageMaterial/DashBoardManageMaterialComponent.tsx
  src/pages/BrandManagement/ManageMaterial/DashboardManageMaterial/DashBoardMaterialStyle.module.scss
  src/pages/BrandManagement/ManageMaterial/MaterialManage/EditMaterial/EditMaterialPopUpScreens.tsx
  src/pages/BrandManagement/ManageMaterial/MaterialManage/EditMaterial/EditMaterialPopUpStyles.module.scss
  src/pages/BrandManagement/ManageMaterial/MaterialManage/MaterialManageScreens.tsx
  src/pages/BrandManagement/index.tsx
  src/pages/DetailProduct/ProductDetail/ProductDetailScreens.tsx
  src/pages/FilterProduct/ProductFilterScreen/FilterProductScreen.tsx
  src/pages/FilterProduct/ProductFilterScreen/FilterProductStyles.scss
  src/pages/FilterProduct/index.tsx
Labels: create, feature, reviewing

#42 [FE0040] Update to add item to draggable elements
  package-lock.json
  package.json
  src/App.jsx
  src/api/ApiConfig.tsx
  src/canvas/CanvasModel.jsx
  src/canvas/Hoodie.jsx
  src/canvas/LongSkirt.jsx
  src/canvas/LongSkirtModel2.jsx
  src/canvas/Shirt.jsx
  src/canvas/WomanSkirtTop.jsx
  src/canvas/WomenSkirtDown.jsx
  src/canvas/WomenSkirtFull.jsx
  src/components/ColorPicker/ColorPicker.jsx
  src/components/FilePicker/FilePicker.jsx
  src/components/Tab/Tab.jsx
  src/models/DesignModel.tsx
  src/pages/AdminManagement/AdminProfile/AdminProfileScreens.tsx
  src/pages/CustomDesign/Components/Draggable/ImageDraggableComponent.tsx
  src/pages/CustomDesign/Components/Draggable/ImageDraggableStyle.module.scss
  src/pages/CustomDesign/CustomDesign.module.scss
  src/pages/CustomDesign/CustomDesignScreen.tsx
  src/pages/CustomDesign/Designer/Designer.jsx
  src/pages/CustomDesign/Designer/ImageEditor.jsx
  src/store/index.js
  src/store/index.tsx
  src/utils/DesignerUtils.js
Labels: fIX-bug, update, feature, reviewing

#43 [FE0033] Create order detail and order history
  src/App.jsx
  src/i18n/en.json
  src/i18n/vi.json
  src/pages/Error/Screen404.tsx
  src/pages/Order/OrderDetail/OrderDetailScreen.tsx
  src/pages/Order/OrderDetail/OrderDetailStyles.module.scss
  src/pages/Order/OrderHistory/OrderHistoryScreen.tsx
  src/pages/Order/OrderHistory/OrderHistoryStyles.module.scss
  src/pages/Order/index.tsx
Labels: create, feature, reviewing

#44 [FE0010] Create user profile
  src/App.jsx
  src/pages/Authentication/ProfileSetting/ProfileSettingScreen.tsx
  src/pages/Authentication/ProfileSetting/ProfileSettingStyles.module.scss
  src/pages/Authentication/index.tsx
Labels: create, feature, reviewing

#46 [FE0007] Update refresh token function
  package-lock.json
  package.json
  src/App.jsx
  src/api/ApiConfig.tsx
  src/components/Header/HeaderComponent.tsx
  src/components/ImageMasonry/ImageMasonryCoponent.tsx
  src/components/ImageMasonry/ImageMasonryStyle.module.scss
  src/pages/Authentication/Components/AuthDiaglog/TokenRefreshDialogComponent.tsx
  src/pages/Authentication/ForgotpassWord/ForgotPassWordScreen.tsx
  src/pages/Authentication/SignIn/SignInDialog.tsx
  src/pages/Authentication/SignIn/SignInScreen.tsx
  src/pages/Authentication/SignIn/SignInStyle.module.scss
  src/pages/Authentication/SignUp/SignUpScreen.tsx
  src/pages/Authentication/SignUp/SignUpStyle.module.scss
  src/pages/Authentication/VerifyEmail/VerifyEmailScreen.tsx
  src/pages/Authentication/index.tsx
  src/pages/CustomDesign/CustomDesignScreen.tsx
  src/pages/CustomDesign/Designer/Designer.jsx
  src/pages/CustomDesign/Designer/ImageEditor.jsx
  src/pages/Home/HomeScreen.tsx
  src/pages/Order/OrderDetail/OrderDetailScreen.tsx
  src/pages/Order/OrderHistory/OrderHistoryScreen.tsx
Labels: create, update, feature, reviewing

#47 [FE0040] Update design screen draggable element
  package-lock.json
  package.json
  src/assets/clothes/shirt-back-design.png
  src/assets/clothes/shirt-front-design.png
  src/assets/index.js
  src/canvas/Hoodie.jsx
  src/canvas/Shirt.jsx
  src/canvas/example.tsx
  src/components/ColorPicker/ColorPicker.module.scss
  src/components/FilePicker/FilePicker.jsx
  src/components/OptionFilter/OptionFilterCompnent.tsx
  src/components/TextEditor/TextEditor.tsx
  src/components/TextEditor/TextEditorStyle.module.scss
  src/components/index.js
  src/index.css
  src/models/DesignModel.tsx
  src/models/ProductModel.tsx
  src/pages/CustomDesign/Components/Dialog/ProductDialogComponent.tsx
  src/pages/CustomDesign/Components/Dialog/ProductDialogStyle.module.scss
  src/pages/CustomDesign/Components/Draggable/ImageDraggableComponent.tsx
  src/pages/CustomDesign/Components/ItemEditorTools/ItemEditorToolsComponent.tsx
  src/pages/CustomDesign/Components/ItemEditorTools/ItemEditorToolsStyle.module.scss
  src/pages/CustomDesign/CustomDesign.module.scss
  src/pages/CustomDesign/CustomDesignScreen.tsx
  src/pages/CustomDesign/Designer/Designer.jsx
  src/utils/DesignerUtils.js
Labels: fIX-bug, create, update, feature, reviewing

#48 [FE0007] Update verify component
  src/App.jsx
  src/api/ApiConfig.tsx
  src/components/Header/HeaderComponent.tsx
  src/models/UserModel.tsx
  src/pages/Authentication/Components/AuthDiaglog/TokenRefreshDialogComponent.tsx
  src/pages/Authentication/ForgotpassWord/ForgotPassWordScreen.tsx
  src/pages/Authentication/SignIn/SignInScreen.tsx
  src/pages/Authentication/SignIn/SignInStyle.module.scss
  src/pages/Authentication/SignUp/SignUpScreen.tsx
  src/pages/Authentication/VerifyEmail/VerifyEmailScreen.tsx
  src/pages/Home/HomeScreen.tsx
Labels: fIX-bug, update, feature, reviewing

#49 [FE0042] Create material input dialog in Design screen
  src/canvas/CanvasModel.jsx
  src/canvas/Shirt.jsx
  src/components/ChooseMaterialDialog/ChooseMaterialDialogComponent.tsx
  src/components/ChooseMaterialDialog/ChooseMaterialDialogStyle.module.scss
  src/components/index.js
  src/i18n/en.json
  src/i18n/vi.json
  src/index.module.scss
  src/models/DesignModel.tsx
  src/pages/CustomDesign/Components/MaterialDetail/MaterialDetailComponent.tsx
  src/pages/CustomDesign/Components/MaterialDetail/MaterialDetailStyle.module.scss
  src/pages/CustomDesign/CustomDesign.module.scss
  src/pages/CustomDesign/CustomDesignScreen.tsx
  src/root/ColorSystem.tsx
Labels: create, feature, reviewing

#50 [FE0043] Create order product screen
  src/App.jsx
  src/pages/Order/OrderProduct/OrderProductScreen.tsx
  src/pages/Order/OrderProduct/OrderProductStyle.module.scss
  src/pages/Order/index.tsx
Labels: create, feature, reviewing

#53 [FE0040] Update material dialog
  src/assets/clothes/hoodie-model.png
  src/canvas/Hoodie.jsx
  src/canvas/Shirt.jsx
  src/components/ChooseMaterialDialog/ChooseMaterialDialogComponent.tsx
  src/components/Loading/LoadingComponent.tsx
  src/components/TextEditor/TextEditor.tsx
  src/models/CustomerProfileModel.tsx
  src/models/DesignModel.tsx
  src/pages/Authentication/ProfileSetting/ProfileSettingScreen.tsx
  src/pages/CustomDesign/Components/Draggable/ImageDraggableComponent.tsx
  src/pages/CustomDesign/Components/MaterialDetail/MaterialDetailComponent.tsx
  src/pages/CustomDesign/CustomDesignScreen.tsx
  src/pages/Order/OrderProduct/ChangeAddressDialogComponent.tsx
  src/pages/Order/OrderProduct/OrderProductScreen.tsx
  src/pages/Order/OrderProduct/OrderProductStyle.module.scss
  src/pages/Order/index.tsx
Labels: fIX-bug, update, feature, reviewing
